'use strict';
const inventoryLabelTypes=[['frontLabel','Front label'],['nutritionLabel','Nutrition label']];
function labelImage(record,kind){return record?.[kind]||(kind==='frontLabel'?record?.file:null)}
function isLabelImage(file){return !!file&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=\s]+$/.test(file.data)}
function inventoryLabel(record){return '<div class="inventory-labels">'+inventoryLabelTypes.map(([kind,title])=>{const file=labelImage(record,kind);return isLabelImage(file)?`<button class="inventory-label" data-label="${esc(record.id)}" data-label-kind="${kind}"><img src="${esc(file.data)}" alt="${title} for ${esc(record.name)}"><span>View ${title.toLowerCase()}</span></button>`:`<p class="label-missing">${title} image missing · Edit to add one</p>`}).join('')+'</div>'}
function inventoryLabelFields(record){return inventoryLabelTypes.map(([kind,title])=>{const file=labelImage(record,kind);return `<label class="field">${title} image (required, up to 2 MB)<input name="${kind}" type="file" accept="image/png,image/jpeg,image/webp" ${isLabelImage(file)?'':'required'}></label>${isLabelImage(file)?`<img class="inventory-label-preview" src="${esc(file.data)}" alt="Current ${title.toLowerCase()}"><p>Current ${title.toLowerCase()} is kept unless replaced.</p>`:'<p>PNG, JPEG, or WebP only.</p>'}`}).join('')}
function previewInventoryLabel(record,kind){const file=labelImage(record,kind);if(!isLabelImage(file))return;const title=inventoryLabelTypes.find(([key])=>key===kind)?.[1]||'Label';const dialog=document.createElement('dialog');dialog.className='label-dialog';dialog.setAttribute('aria-label',title);dialog.innerHTML=`<div class="section-head"><h2>${esc(record.name)} — ${title.toLowerCase()}</h2><button aria-label="Close label preview">×</button></div><img src="${esc(file.data)}" alt="${title} for ${esc(record.name)}"><button data-download>Download ${title.toLowerCase()}</button>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.querySelector('[data-download]').onclick=()=>download(file.data,file.name);dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal()}
async function readInventoryLabels(form,existing){const result={};for(const [kind,title] of inventoryLabelTypes){const file=form.get(kind);if(file&&file.size){if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error(`${title}: choose a PNG, JPEG, or WebP image under 2 MB.`);try{const bitmap=await createImageBitmap(file);bitmap.close()}catch{throw Error(`${title}: this file could not be read as an image.`)}result[kind]={name:file.name,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error(`${title}: the image could not be loaded.`));reader.readAsDataURL(file)})}}else{const current=labelImage(existing,kind);if(!isLabelImage(current))throw Error(`${title} image is required.`);result[kind]=current}}return result}
const $=s=>document.querySelector(s), key='cc-kitchen-v1';
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>iso(new Date()), parse=s=>new Date(s+'T12:00:00'), age=(a,b=today())=>Math.round((Date.UTC(...b.split('-').map((v,i)=>i===1?+v-1:+v))-Date.UTC(...a.split('-').map((v,i)=>i===1?+v-1:+v)))/86400000);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db={version:1,start:today(),days:{},inventory:[],shopping:[],mileage:[],labels:[],documents:[]};
try{const raw=localStorage.getItem(key),saved=JSON.parse(raw);if(saved&&valid(saved))db=saved;else if(raw===null)localStorage.setItem(key,JSON.stringify(db));else throw Error('Invalid saved data')}catch(e){setTimeout(()=>notify('Saved data could not be read. Restore a backup before adding records.'),100)}
let selected=today(),month=parse(selected),view='calendar',edit=null;
const names={substitutions:'Substitutions',compliance:'Compliance Guide',calendar:'Daily overview',menu:'Menu',deliveries:'Receiving deliveries',inventory:'Inventory',shopping:'Shopping list',mileage:'Mileage log',labels:'Product labels',documents:'Paperwork library'};
const defaults=[['Meal production & meal counts','Menu, portions prepared, portions served, and meal counts.'],['Food safety records','Record temperatures and complete your facility’s safety checks.'],['Inventory check','Review supplies, expiration dates, and items to reorder.'],['Product documentation','Review CN labels or PFS documentation for products used.']];
function valid(x){return x&&validSubstitutions(x.substitutions)&&validDeliveries(x.deliveries)&&validMileageRoutes(x.mileageRoutes)&&validInventoryAliases(x.inventoryAliases)&&validMenus(x.menus)&&x.version===1&&/^\d{4}-\d{2}-\d{2}$/.test(x.start)&&x.days&&typeof x.days==='object'&&['inventory','shopping','mileage','labels','documents'].every(k=>Array.isArray(x[k]))&&Object.values(x.days).every(d=>Array.isArray(d.tasks)&&d.tasks.every(t=>typeof t.title==='string'))}
function save(){try{localStorage.setItem(key,JSON.stringify(db));return true}catch(e){notify('Storage is full or unavailable. Download a backup now.');return false}}
function notify(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',5000)}
function dayData(date){if(db.days[date])return db.days[date];const weekday=parse(date).getDay();return {tasks:date>=db.start&&weekday!==0&&weekday!==6?defaults.map((t,i)=>({id:'default-'+i,title:t[0],detail:t[1],done:false})):[]}}
function status(date){const tasks=dayData(date).tasks;if(!tasks.length)return 'neutral';if(tasks.every(t=>t.done))return 'green';if(date>today())return 'neutral';return age(date)>7?'red':'yellow'}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewLabel').textContent=names[view];if(view==='calendar')renderCalendar();else if(view==='menu')renderMenu();else if(view==='deliveries')renderDeliveries();else if(view==='substitutions')renderSubstitutions();else if(view==='compliance')renderComplianceGuide();else renderRecords()}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth(),total=new Date(y,m+1,0).getDate(),dates=Array.from({length:total},(_,i)=>iso(new Date(y,m,i+1))),counts={green:0,yellow:0,red:0};dates.forEach(d=>{const s=status(d);if(s in counts)counts[s]++});const d=dayData(selected),done=d.tasks.filter(t=>t.done).length;
$('#content').innerHTML=`<div class="page-title"><div><div class="eyebrow">YOUR KITCHEN, IN ORDER</div><h1>Daily overview</h1><p>A clear view of what’s done and what needs your attention.</p></div><button class="primary" id="addTask">+ Add task</button></div><div class="stats"><div class="stat"><strong style="color:var(--success)">${counts.green}</strong><span>Completed days</span></div><div class="stat"><strong style="color:var(--warning)">${counts.yellow}</strong><span>Days to catch up</span></div><div class="stat"><strong style="color:var(--danger)">${counts.red}</strong><span>Days overdue</span></div></div><section class="panel"><div class="section-head"><h2>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div class="month-actions"><button id="prev" aria-label="Previous month">‹</button><button id="today">Today</button><button id="next" aria-label="Next month">›</button></div></div><div class="week">${['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar">${'<span></span>'.repeat(new Date(y,m,1).getDay())}${dates.map(date=>{const s=status(date),tasks=dayData(date).tasks,n=tasks.filter(t=>t.done).length;return `<button class="day ${s} ${date===selected?'selected':''} ${date===today()?'today':''}" data-date="${date}" aria-pressed="${date===selected}" aria-label="${date}, ${s==='green'?'complete':s==='red'?'overdue':s==='yellow'?'outstanding':'no records due'}"><b>${parse(date).getDate()}</b><small>${tasks.length?`${n}/${tasks.length} ${s==='red'?'overdue':s==='green'?'done':'done'}`:'—'}</small></button>`}).join('')}</div><div class="legend"><span><i class="dot green"></i>Complete</span><span><i class="dot yellow"></i>Outstanding · 0–7 days</span><span><i class="dot red"></i>Incomplete · over 7 days</span><span>— No records due</span></div></section><section class="panel"><div class="daily-top"><div><div class="eyebrow">DAILY CHECKLIST</div><h2>${parse(selected).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h2></div><span class="badge ${status(selected)}">${done} of ${d.tasks.length} complete</span></div><div class="progress"><div style="width:${d.tasks.length?done/d.tasks.length*100:0}%"></div></div>${d.tasks.length?d.tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><input id="task-${i}" type="checkbox" data-task="${i}" ${t.done?'checked':''}><label for="task-${i}"><span>${esc(t.title)}</span><small>${esc(t.detail||'')}${t.completedAt?' · Completed '+esc(t.completedAt)+(age(selected,t.completedAt)>7?' (late)':''):''}</small></label><button data-note="${i}">Record</button></div>`).join(''):'<div class="empty">No tasks scheduled for this day.<br>Add a task for a workday, shopping trip, or special objective.</div>'}<p style="font-size:12px;margin-top:15px">Weekday checklists begin ${esc(db.start)}. Completed days stay green; late completion is recorded.</p></section>`;
$('#prev').onclick=()=>{month=new Date(y,m-1,1);render()};$('#next').onclick=()=>{month=new Date(y,m+1,1);render()};$('#today').onclick=()=>{selected=today();month=parse(selected);render()};$('#addTask').onclick=()=>openForm('task');document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;render()});document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{const data=structuredClone(dayData(selected)),t=data.tasks[+b.dataset.task];t.done=b.checked;t.completedAt=b.checked?today():null;db.days[selected]=data;save();render()});document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openForm('taskRecord',+b.dataset.note));}
const fields={inventory:[['name','Item'],['quantity','Quantity','number'],['unit','Unit (lb, cans, cases…)'],['minimum','Reorder at or below','number'],['expires','Expiration / use-by date','date'],['location','Storage location']],shopping:[['name','Item'],['quantity','Quantity / size'],['store','Store'],['cost','Actual cost ($)','number'],['purchased','Purchased','checkbox']],mileage:[['name','Trip purpose'],['date','Trip date','date'],['route','From → to'],['start','Starting odometer','number'],['end','Ending odometer','number']],labels:[['name','Product and manufacturer'],['type','Documentation type','select'],['code','CN number / product code'],['portion','Serving size and meal pattern contribution'],['reviewer','Reviewer'],['date','Review date','date'],['match','Documentation matches the actual product and serving size','checkbox'],['credit','Crediting information checked against current guidance','checkbox'],['evidence','Supporting document attached or retained at location below','checkbox'],['location','Original document / invoice location']],documents:[['name','Document title'],['date','Record date','date'],['program','Program','program'],['notes','Notes / filing location','textarea']],task:[['title','Task title'],['detail','Instructions / objective','textarea']],taskRecord:[['detail','Record notes / document location','textarea']]};
function renderRecords(){let rows=db[view];const low=view==='inventory'?rows.filter(r=>+r.quantity<=+r.minimum).length:0;const distance=view==='mileage'?rows.reduce((n,r)=>n+(+r.end- +r.start),0):0;
$('#content').innerHTML=`<div class="page-title"><div><div class="eyebrow">KITCHEN RECORDS</div><h1>${names[view]}</h1><p>${view==='mileage'?distance.toFixed(1)+' miles logged':view==='inventory'?`${rows.length} items · ${low} at or below reorder level`:view==='shopping'?`${rows.filter(r=>!r.purchased).length} items left to buy`:`${rows.length} saved records`}</p></div><div class="record-page-actions">${view==='inventory'?'<button id="inventoryAliases">Aliases</button><button id="scanReceipt">Scan receipt</button>':''}<button id="addRecord" class="primary">+ Add ${view==='mileage'?'trip':view==='documents'?'document':'item'}</button></div></div>${view==='labels'?'<div class="note">Keep the CN label or manufacturer’s Product Formulation Statement (PFS) for the product you use. A PFS is not USDA-approved. These checks document your review; they do not certify compliance. <a href="https://www.fna.usda.gov/cn/manufacturer-documentation" target="_blank" rel="noopener">USDA documentation guidance ↗</a></div>':''}<section class="panel">${rows.length?rows.map(r=>`<article class="record"><div><strong>${esc(r.name)}</strong><p>${summary(r)}</p>${view==='inventory'?inventoryLabel(r):''}${view!=='inventory'&&r.file?`<button data-file="${esc(r.id)}">↓ ${esc(r.file.name)}</button>`:''}</div><div class="record-actions"><button data-edit="${esc(r.id)}">Edit</button><button data-delete="${esc(r.id)}" aria-label="Delete ${esc(r.name)}">Delete</button></div></article>`).join(''):`<div class="empty"><h3>No ${names[view].toLowerCase()} records yet</h3><p>${view==='labels'?'Add your first product and keep its supporting documentation together.':'Add a record to start tracking your kitchen’s work.'}</p></div>`}</section>${view==='mileage'?mileageRouteLibrary():''}`;if(view==='mileage')bindMileageRoutes();$('#addRecord').onclick=()=>openForm(view);if(view==='inventory'){$('#scanReceipt').onclick=openReceiptScanner;$('#inventoryAliases').onclick=openInventoryAliases;}document.querySelectorAll('[data-label]').forEach(b=>b.onclick=()=>previewInventoryLabel(rows.find(r=>r.id===b.dataset.label),b.dataset.labelKind));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(view,b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this record from this device?')){db[view]=db[view].filter(r=>r.id!==b.dataset.delete);save();render()}});document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{const f=rows.find(r=>r.id===b.dataset.file).file;download(f.data,f.name)})}
function summary(r){if(view==='inventory')return `${esc(r.quantity)} ${esc(r.unit)} · ${esc(r.location)}${r.expires?' · Use by '+esc(r.expires):''}${+r.quantity<=+r.minimum?' · REORDER':''}`;if(view==='shopping')return `${r.purchased?'✓ Purchased':'To buy'} · ${esc(r.quantity)} · ${esc(r.store)}${r.cost?' · $'+Number(r.cost).toFixed(2):''}`;if(view==='mileage')return `${esc(r.date)} · ${esc(r.route)} · ${(+r.end- +r.start).toFixed(1)} miles · Odometer ${esc(r.start)} → ${esc(r.end)}${r.calculated?' (calculated)':''}${r.routeUrl&&validMapsLink(r.routeUrl)?` · <a href="${esc(r.routeUrl)}" target="_blank" rel="noopener noreferrer">Open route ↗</a>`:''}`;if(view==='labels')return `${esc(r.type)} · ${r.match&&r.credit&&r.evidence&&r.reviewer&&r.date?'Review recorded':'Needs review'}\n${esc(r.portion)}${r.reviewer?' · '+esc(r.reviewer):''}`;return `${esc(r.date)} · ${esc(r.program)}\n${esc(r.notes)}`}
function shoppingInventoryPicker(record){const names=[...new Set(db.inventory.map(item=>String(item.name||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));return `<label class="field">Choose inventory item<select id="shoppingInventoryItem"><option value="">${names.length?'Select an item or type a name below':'No inventory items yet — type a name below'}</option>${names.map(name=>`<option value="${esc(name)}" ${record.name===name?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`}
function openForm(type,id){if(type==='mileage'){openMileageTrip(id);return}edit={type,id};const r=type==='taskRecord'?dayData(selected).tasks[id]:id?db[type].find(r=>r.id===id):{};$('#dialogTitle').textContent=type==='taskRecord'?'Daily task record':type==='task'?'Add a task':`${id?'Edit':'Add'} ${type==='mileage'?'trip':'record'}`;$('#formError').textContent='';$('#fields').innerHTML=(type==='shopping'?shoppingInventoryPicker(r):'')+fields[type].map(([name,label,input='text'])=>{const value=r[name]??(input==='date'&&name!=='expires'?selected:'');return input==='checkbox'?`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`:`<label class="field">${label}${input==='textarea'?`<textarea name="${name}">${esc(value)}</textarea>`:input==='select'||input==='program'?`<select name="${name}">${(input==='select'?['CN label','Product Formulation Statement']:['Both programs','Early Head Start','Head Start']).map(v=>`<option ${value===v?'selected':''}>${v}</option>`).join('')}</select>`:`<input name="${name}" type="${input}" value="${esc(value)}" ${['name','title','quantity','start','end'].includes(name)?'required':''} ${input==='number'?'min="0" step="any"':''}>`}</label>`}).join('')+(type==='inventory'?inventoryLabelFields(r):'')+(!['task','inventory','shopping','mileage'].includes(type)?`<label class="field">Attach supporting document (PDF or image, up to 2 MB)<input name="attachment" type="file" accept="application/pdf,image/png,image/jpeg,image/webp"></label>${r.file?'<p>Existing attachment is kept unless replaced.</p>':''}`:'');if(type!=='inventory'&&r.file){const b=document.createElement('button');b.type='button';b.textContent='Download current attachment';b.onclick=()=>download(r.file.data,r.file.name);document.querySelector('#fields').append(b)}if(type==='shopping'){const picker=document.querySelector('#shoppingInventoryItem');picker.onchange=()=>{if(picker.value)document.querySelector('#recordForm [name="name"]').value=picker.value}}document.querySelector('#editor').showModal()}
$('#recordForm').onsubmit=async e=>{e.preventDefault();const {type,id}=edit,form=new FormData(e.target),r={};for(const [name,,input] of fields[type])r[name]=input==='checkbox'?form.has(name):String(form.get(name)||'').trim();if((r.name!==undefined&&!r.name)||(r.title!==undefined&&!r.title)){$('#formError').textContent='Please enter a title.';return}if(type==='mileage'&&+r.end<+r.start){$('#formError').textContent='Ending odometer must be at least the starting odometer.';return}if(type==='inventory'){try{Object.assign(r,await readInventoryLabels(form,db.inventory.find(item=>item.id===id)))}catch(error){$('#formError').textContent=error.message;return}}else{const file=form.get('attachment');if(file&&file.size){if(file.size>2*1024*1024||!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type)){$('#formError').textContent='Choose a PDF, PNG, JPEG, or WebP file under 2 MB.';return}r.file={name:file.name,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}}}const before=structuredClone(db);if(type==='task'||type==='taskRecord'){const d=structuredClone(dayData(selected));if(type==='task')d.tasks.push({...r,id:crypto.randomUUID(),done:false});else Object.assign(d.tasks[id],r);db.days[selected]=d}else if(id)Object.assign(db[type].find(r=>r.id===id),r);else db[type].push({...r,id:crypto.randomUUID()});if(type==='inventory'&&id)delete db.inventory.find(item=>item.id===id).file;if(!save()){db=before;$('#formError').textContent='Could not save. Storage may be full; try a smaller attachment.';return}$('#editor').close();render();notify('Record saved')};
$('#closeDialog').onclick=()=>$('#editor').close();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click()}
$('#backup').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));download(url,`kitchen-backup-${today()}.json`);setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const value=JSON.parse(await f.text());if(!valid(value))throw Error();if(confirm('Replace all current records with this backup? Download a backup first if you need to keep them.')){const old=db;db=value;if(!save())db=old;else{resetMenu();render();notify('Backup restored')}}}catch{notify('This file is not a valid Kitchen Hub backup.')}e.target.value=''};
render();


