import {generateDemo} from './demo.js';
import {rooms,meals,schemas,sources,sections} from './schema.js';
import {emptyState,localDate,monday,encodeMenu,decodeMenu,stock,validateRecord,validateBackup,storageDefaults} from './model.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=emptyState(),db,section='today',selectedDate=localDate(),week=monday(localDate()),logType='cold',inventoryType='product',dietType='diets',menuDirty=false;
let stateKey='state',activeRole='Lead Cook';
const role=()=>$('#role').value;
$('#role').value='Lead Cook';
const notify=message=>{const t=$('#toast');t.textContent=message;t.style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.style.display='none',5500);};
function info(key){const s=sources[key];return `<span class="info"><button type="button" aria-label="Requirements for ${esc(s.title)}">i</button><span class="tip" role="tooltip"><b>${esc(s.rule)}</b><br>${esc(s.text)}${s.links.map(([u,t])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`).join('')}</span></span>`;}
function heading(title,key,level=2){return `<h${level}>${esc(title)}${info(key)}</h${level}>`;}
function head(title,subtitle,key,tools=''){return `<div class="page-head"><div><span class="eyebrow">HEAD START / EARLY HEAD START</span>${heading(title,key,1)}<p>${esc(subtitle)}</p></div>${tools}</div>`;}
function dateControl(){return `<label>Working date<input id="working-date" type="date" value="${selectedDate}" required></label>`;}
function activeDiets(){return state.records.filter(r=>r.type==='diets'&&r.date<=selectedDate&&(!r.end||r.end>=selectedDate));}
function dietStatus(d){return state.records.find(r=>r.type==='presence'&&r.date===selectedDate&&r.dietId===d.id);}
function resolve(r,key,value){if(key==='productId'){const p=state.records.find(x=>x.id===value);return p?`${p.name} (${p.unit})`:value;}if(key==='dietId'){const d=state.records.find(x=>x.id===value);return d?`${d.room} · ${d.initials} · ${d.localRef}`:value;}return value;}
function safePhoto(v){return /^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v||'');}
function details(r){const fields=[{key:'date',label:r.type==='diets'?'Effective from':'Date'},...schemas[r.type].fields,{key:'operator',label:'Entered by staff initials'},{key:'role',label:'Working role'},{key:'updatedAt',label:'Last saved'},{key:'id',label:'Record ID'}];return `<dl>${fields.filter(f=>r[f.key]!==''&&r[f.key]!==undefined).map(f=>`<dt>${esc(f.label)}</dt><dd>${f.type==='photo'&&safePhoto(r[f.key])?`<img class="photo" src="${r[f.key]}" alt="${esc(f.label)}">`:esc(resolve(r,f.key,r[f.key]))}</dd>`).join('')}</dl>`;}
function titleFor(r){return [r.date,r.room||r.name||resolve(r,'productId',r.productId)||r.equipment||r.food||r.area||r.topic||r.reference||resolve(r,'dietId',r.dietId),r.meal||r.kind||r.category||r.process||r.presence].filter(Boolean).join(' · ');}
function recordsList(type){const records=state.records.filter(r=>r.type===type).sort((a,b)=>b.date.localeCompare(a.date));return records.length?records.map(r=>`<details class="record"><summary>${esc(titleFor(r))} ${r.review==='Pending'?'<span class="pill">Needs review</span>':''}</summary>${details(r)}<button data-edit="${r.id}">Edit record</button> <span class="help">${state.history.filter(h=>h.recordId===r.id).length} saved revision(s)</span></details>`).join(''):'<div class="empty">No records yet.<br>Add your first entry to begin the log.</div>';}
async function load(key=stateKey){return new Promise((resolve,reject)=>{const tx=db.transaction('data','readonly');const req=tx.objectStore('data').get(key);req.onsuccess=()=>resolve(req.result||emptyState());req.onerror=()=>reject(req.error);});}
async function commit(next,description,recordId,before){
 next.history.push({id:crypto.randomUUID(),at:new Date().toISOString(),date:localDate(),role:role(),description,recordId:recordId||'',before:before||null});
 const previousRevision=state.revision;next.revision=previousRevision+1;
 await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite'),store=tx.objectStore('data'),req=store.get(stateKey);let conflict=false;req.onsuccess=()=>{if((req.result?.revision||0)!==previousRevision){conflict=true;tx.abort();return;}store.put(next,stateKey);};tx.oncomplete=resolve;tx.onabort=()=>reject(Error(conflict?'Another tab saved changes. Reload this page before trying again; your unsaved form is still visible.':'Save failed. Export a backup and check browser storage.'));tx.onerror=()=>reject(tx.error);});
 state=next;notify('Saved on this browser');
}
function render(){
 $('#nav').innerHTML=[...sections,...(role()==='Debug'?[['debug','Debug generator','⚙']]:[])].map(([id,title,icon])=>`<button data-nav="${id}" class="${id===section?'active':''}" ${id===section?'aria-current="page"':''}><span class="nav-icon">${icon}</span>${title}</button>`).join('');
 const views={debug:renderDebug,today:renderToday,menu:renderMenu,counts:()=>renderRecords('counts'),diets:renderDiets,inventory:renderInventory,logs:renderLogs,reports:renderReports,sources:renderSources};$('#main').innerHTML=(role()==='Debug'?`<div class="banner warning"><b>DEBUG · SYNTHETIC DATA</b> · Separate test workspace. Reports are samples. <form id="demo-form" class="report-toolbar"><label>From<input name="from" type="date" value="${role()==='Debug'&&state.demoFrom?state.demoFrom:monday(selectedDate)}" required></label><label>Through<input name="through" type="date" value="${state.demoThrough||selectedDate}" required></label>${[['children','Children (age 1+) ',68,74,200],['infants','Infants',0,4,12],['adults','Adults',10,12,50]].map(([key,label,min,max,cap])=>`<fieldset><legend>${label} served</legend><label>Min<input aria-label="${label} minimum" name="${key}Min" type="number" min="0" max="${cap}" step="1" value="${state[key+'Min']??min}" required></label><label>Max<input aria-label="${label} maximum" name="${key}Max" type="number" min="0" max="${cap}" step="1" value="${state[key+'Max']??max}" required></label></fieldset>`).join('')}<p class="help">Facility totals per meal. Counts vary by day; the same group attends all three meals. Infants are additional to age-1+ children and appear in EHS rooms.</p><button class="primary">Generate sample data</button></form><p class="help">Weekdays only · Maximum 31 calendar days · Replaces Debug data only.</p><div id="demo-status" role="status"></div></div>`:'')+views[section]();
 bindView();
}
function dailyObjectives(){
 const today=state.records.filter(r=>r.date===selectedDate),saved=type=>today.filter(r=>r.type===type);
 const units=[...new Set(state.records.filter(r=>r.type==='cold'&&r.date<=selectedDate).map(r=>r.equipment.trim().toLowerCase()))];
 const checked=new Set(saved('cold').map(r=>r.equipment.trim().toLowerCase()));
 const menu=decodeMenu(state.menus[monday(selectedDate)]||''),day=(new Date(selectedDate+'T12:00:00').getDay()+6)%7;
 const objectives=[
 {title:'Plan today’s menu',source:'menu',n:meals.filter(m=>menu[`${day}.${m.toLowerCase()}`]?.trim()).length,total:3,detail:'Breakfast, lunch and snack menu entries',action:'data-nav="menu"'},
 {title:'Check cold storage',source:'cold',n:units.filter(u=>checked.has(u)).length,total:Math.max(1,units.length),detail:units.length?'One submitted check per saved unit':'Submit your first unit check to start the equipment list',action:'data-new="cold"'},
 ...meals.map(meal=>({title:`${meal} room forms`,source:'counts',n:rooms.filter(room=>saved('counts').some(r=>r.room===room&&r.meal===meal)).length,total:rooms.length,detail:'One meal-count form for each of the six rooms',action:'data-nav="counts"'})),
 {title:'Record meal production',source:'menu',n:Math.min(1,saved('production').length),total:1,detail:`${saved('production').length} food / batch forms submitted · add every batch`,action:'data-new="production"'},
 {title:'Log cleaning and sanitation',source:'cleaning',n:Math.min(1,saved('cleaning').length),total:1,detail:`${saved('cleaning').length} forms submitted · record each scheduled task`,action:'data-new="cleaning"'}
 ];
 const diets=activeDiets();if(diets.length)objectives.push({title:'Confirm dietary attendance',source:'diets',n:diets.filter(d=>saved('presence').some(p=>p.dietId===d.id)).length,total:diets.length,detail:'Daily status for each active dietary plan',action:'data-new="presence"'});
 const complete=objectives.filter(o=>o.n>=o.total).length;
 return `<section class="panel objectives"><div class="panel-head"><div><p class="quest-label">DAILY OBJECTIVES</p>${heading('Your kitchen mission','reports')}</div><span class="quest-score">${complete} / ${objectives.length} complete</span></div><progress class="quest-progress" aria-label="Daily form objectives completed" value="${complete}" max="${objectives.length}"></progress><p class="help">${complete===objectives.length?'Daily checklist submitted. Review your records and any additional checks below.':'Save a form to make progress. Your checklist updates automatically.'}</p><ul class="quest-list">${objectives.map(o=>`<li class="quest ${o.n>=o.total?'quest-done':''}"><span class="quest-check" aria-hidden="true">${o.n>=o.total?'✓':'◇'}</span><div><strong>${esc(o.title)}</strong>${info(o.source)}<p class="help">${esc(o.detail)}</p></div><span class="quest-count">${o.n} / ${o.total}<small>${o.n>=o.total?'Submitted':'To do'}</small></span><button ${o.action}>${o.n>=o.total?'Open':'Continue'} ↗</button></li>`).join('')}</ul><details class="quest-extra"><summary>Additional objectives · when applicable</summary><p class="help">Use these for the equipment, food processes and events that apply today.</p><div class="toolbar">${['thermal','cooling','dishwasher','sanitizer','receiving','use','waste','infant','corrective'].map(type=>`<button data-new="${type}">${esc(schemas[type].title)} · ${saved(type).length} submitted</button>`).join('')}</div></details></section>`;
}
function renderToday(){
 const records=state.records.filter(r=>r.type==='counts'&&r.date===selectedDate),sums=Object.fromEntries(['requested','prepared','served','reimbursable'].map(k=>[k,records.filter(r=>k!=='reimbursable'||r.review==='Reviewed').reduce((s,r)=>s+Number(r[k]||0),0)]));
 const open=state.records.filter(r=>r.type==='corrective'&&r.status!=='Closed').length,ds=activeDiets(),pending=records.filter(r=>r.review!=='Reviewed').length;
 return head('A good day starts in the kitchen.','Plan the meals. Record the service. Keep the details together.','counts',dateControl())+`<div class="banner"><b>Kitchen handoff</b> · ${records.length} of 18 room-meal records entered · ${pending} awaiting review · ${open} open corrective action${open===1?'':'s'}</div>${dailyObjectives()}<div class="grid-two"><section class="panel"><div class="panel-head">${heading('The six rooms','counts')}<button data-nav="counts">Enter meal counts ↗</button></div>${rooms.map((room,i)=>{const rs=records.filter(r=>r.room===room);return `<div class="room-row"><div><span class="room-symbol">${i<2?'E':'H'}</span><b>${room.replace(/^(EHS|HS) /,'')}</b><small>${i<2?'Early Head Start':'Head Start'} · ${rs.map(r=>r.meal).join(', ')||'No service records yet'}</small></div><span class="pill">${rs.length} / 3 meals</span></div>`;}).join('')}</section><div><section class="panel"><div class="panel-head">${heading('Dietary handoff','diets')}<button data-nav="diets">View</button></div>${ds.length?ds.map(d=>{const p=dietStatus(d);return `<div class="room-row"><div><b>${esc(d.initials)} · ${esc(d.room)}</b><p class="help">${esc(d.category)} · ${esc(d.substitute)}</p></div><span class="pill">${esc(p?`${p.presence} · ${p.meals}`:'Confirm attendance')}</span></div>`;}).join(''):'<div class="empty">No active dietary plans.<br>Add initials and preparation instructions in Dietary needs.</div>'}</section><section class="panel">${heading('Start with the essentials','thermal')}<p class="help">Record storage checks, review dietary changes, then confirm the classroom service sheets.</p><div class="toolbar"><button data-new="cold">+ Storage check</button><button data-nav="menu">Plan menu</button></div></section></div></div><p class="help">Objectives track saved forms for the selected date. Complete all applicable batches and checks; submission is not a compliance approval.</p>`;
}
function renderMenu(){const values=decodeMenu(state.menus[week]||'');return head('The weekly menu','Five days, three meals. Edit any cell and save the week.','menu',`<label>Week of Monday<input type="date" id="week" value="${week}"></label>`)+`<div class="banner warning">Menu planning draft · Record age-specific portions, components and actual substitutions in production records. Free-text entries are not automatically approved for reimbursement.</div><section class="panel"><form id="menu-form"><div class="table-wrap"><table class="menu"><thead><tr><th>Day</th>${meals.map(m=>`<th>${m}</th>`).join('')}</tr></thead><tbody>${['Monday','Tuesday','Wednesday','Thursday','Friday'].map((day,i)=>`<tr><th scope="row">${day}</th>${meals.map(m=>{const k=`${i}.${m.toLowerCase()}`;return `<td><textarea aria-label="${day} ${m}" name="${k}" placeholder="Foods, components, substitutions…">${esc(values[k]||'')}</textarea></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><div class="form-actions"><span id="menu-status" class="help">${state.menus[week]?'Saved menu loaded':'No menu saved for this week'}</span><button class="primary">Save week</button></div></form><details><summary class="help">Compact menu representation</summary><p class="help">URL-encoded day.meal=value pairs preserve punctuation and line breaks. The table parses this string on load.</p><textarea readonly aria-label="Compact menu data">${esc(state.menus[week]||'')}</textarea></details></section><section class="panel"><div class="panel-head">${heading('Production records','menu')}<button data-new="production">+ Add food / batch</button></div>${recordsList('production')}</section>`;}
function renderRecords(type){const s=schemas[type];return head(s.title,s.description,s.source,`<button class="primary" data-new="${type}">+ Add record</button>`)+`<section class="panel">${type==='counts'?'<p class="help">Reimbursable stays blank until reviewed. Adult meals are excluded. One room/meal/date entry prevents duplicates. All dates are shown below.</p>':''}${recordsList(type)}</section>`;}
function renderDiets(){return head('Dietary needs','Clear preparation instructions, without child names.','diets',`<button class="primary" data-new="${dietType}">+ Add ${dietType==='diets'?'dietary plan':'daily status'}</button>`)+`<div class="log-tabs">${[['diets','Dietary plans'],['presence','Daily presence / absence']].map(([id,t])=>`<button data-diet-tab="${id}" class="${dietType===id?'active':''}">${t}</button>`).join('')}</div><div class="banner">${esc(schemas[dietType].description)}</div><section class="panel">${recordsList(dietType)}</section><section class="panel">${heading('Dietary categories','diets')}<p class="help">${state.categories.map(esc).join(' · ')}</p><form id="category-form" class="toolbar"><label>Custom category<input name="category" maxlength="80" required></label><button>Add category</button></form></section>`;}
function renderInventory(){const products=state.records.filter(r=>r.type==='product');return head('Inventory','Know what came in, what was used, and what remains.','inventory',`<button class="primary" data-new="${inventoryType}">+ ${inventoryType==='product'?'Add product':inventoryType==='receiving'?'Receive stock':'Record use'}</button>`)+`<div class="log-tabs">${[['product','Products & stock'],['receiving','Receiving'],['use','Use / issue']].map(([id,t])=>`<button data-inventory-tab="${id}" class="${id===inventoryType?'active':''}">${t}</button>`).join('')}<button data-go-waste="true">Waste log ↗</button></div>${inventoryType==='product'?`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>On hand</th><th>Location</th><th>Product / label</th><th></th></tr></thead><tbody>${products.map(p=>`<tr><td><b>${esc(p.name)}</b><p class="help">${esc(p.package)}</p></td><td>${stock(state.records,p.id).toFixed(2)} ${esc(p.unit)}</td><td>${esc(p.location)}</td><td><div class="photo-pair">${['front','back'].map(k=>safePhoto(p[k])?`<img class="photo" src="${p[k]}" alt="${esc(p.name)} ${k}">`:`<span class="help">No ${k} photo</span>`).join('')}</div></td><td><button data-edit="${p.id}">Edit</button></td></tr>`).join('')}</tbody></table></div>${!products.length?'<div class="empty">Add a product, then receive its first lot.<br>Photograph both the front and the ingredients/nutrition label.</div>':''}</section><section class="panel">${heading('Lot balances','inventory')}<div class="table-wrap"><table><thead><tr><th>Product</th><th>Lot</th><th>Remaining</th><th>Earliest expiration / best-by</th></tr></thead><tbody>${products.flatMap(p=>[...new Set(state.records.filter(r=>r.productId===p.id&&r.type==='receiving'&&r.decision==='Accepted').map(r=>r.lot))].map(l=>{const expiry=state.records.filter(r=>r.productId===p.id&&r.lot===l&&r.expiry&&r.decision==='Accepted').map(r=>r.expiry).sort()[0];return `<tr><td>${esc(p.name)}</td><td>${esc(l)}</td><td>${stock(state.records,p.id,l).toFixed(2)} ${esc(p.unit)}</td><td>${esc(expiry||'Not recorded')}</td></tr>`;})).join('')}</tbody></table></div></section>`:`<div class="banner">${esc(schemas[inventoryType].description)}</div><section class="panel">${recordsList(inventoryType)}</section>`}`;}
function renderLogs(){const types=['cold','thermal','cooling','dishwasher','sanitizer','corrective','cleaning','waste','infant','training'];return head('Kitchen logs','Simple records for the work that happens every day.','cleaning')+`<div class="log-tabs">${types.map(t=>`<button data-log-tab="${t}" class="${t===logType?'active':''}">${esc(schemas[t].title)}</button>`).join('')}</div><section class="panel"><div class="panel-head">${heading(schemas[logType].title,schemas[logType].source)}<button class="primary" data-new="${logType}">+ Add record</button></div><p class="help">${esc(schemas[logType].description)}</p>${recordsList(logType)}</section>`;}
function renderReports(){return head('Reports & backup','Select a date range, review the records, and print a kitchen packet.','reports')+`<section class="panel">${heading('Build a printable packet','reports')}<form id="report-form" class="report-toolbar"><label>From<input name="from" type="date" value="${role()==='Debug'&&state.demoFrom?state.demoFrom:monday(selectedDate)}" required></label><label>Through<input name="to" type="date" value="${selectedDate}" required></label><label>Records<select name="type"><option value="all">All kitchen records + menus</option><option value="menus">Weekly menus only</option>${Object.entries(schemas).map(([id,s])=>`<option value="${id}">${esc(s.title)}</option>`).join('')}<option value="history">Revision history</option></select></label><button class="primary">Preview packet</button></form><div id="report-preview"></div></section><section class="panel">${heading('Keep a backup','reports')}<p class="help">Export all records, menu strings, product photos and revision history as JSON. Restore replaces this browser’s dataset after a preview and confirmation. Store backups securely; initials can still identify children.</p><div class="toolbar"><button id="export">Export full backup</button><label>Preview a backup to restore<input id="import" type="file" accept="application/json,.json"></label></div><div id="restore-preview"></div></section><div class="banner warning">Local-first means this browser only. Clearing browser data can remove records. No automatic backup, cross-device sync, secure authentication or claim submission is included.</div>`;}
function renderSources(){return head('Compliance guide','Research checked September 14, 2026 · source links require internet.','reports')+`<div class="banner warning">These are compliance-informed prototype forms, not approved replacements for your sponsor’s records. Confirm the facility’s licensing authority, approved meal-count method, retention schedule and local food-service rules before operational use.</div><section class="panel">${Object.entries(sources).map(([k,s])=>`<article class="source-card">${heading(s.title,k)}<b>${esc(s.rule)}</b><p>${esc(s.text)}</p>${s.links.map(([u,t])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`).join(' · ')}</article>`).join('')}</section><section class="panel">${heading('Meal planning reminders','menu')}<p>Age 1 and age 2 need different milk planning; infant records are separate from the 1–2 and 3–5 child portion patterns. Keep food quantities and crediting documents alongside the menu.</p><p>Since October 1, 2025: cereal ≤6 g added sugars per dry ounce; yogurt ≤2 g per ounce. Include daily whole-grain-rich crediting and check juice frequency.</p><a href="https://www.fns.usda.gov/cn/school-nutrition-standards-updates/added-sugars" target="_blank" rel="noopener noreferrer">USDA added-sugar update ↗</a><p class="help">The research notes in the project explain assumptions, limitations and the next steps for live use. The current Alaska Food Code landing page identifies May 11, 2025 as its last effective change; its linked BASIS text could not be retrieved during this research. Detailed sanitation targets should be checked against the facility’s current code and equipment instructions.</p></section>`;}
function fieldHTML(f,r){let options=f.options||[];if(f.type==='category')options=state.categories;if(f.type==='product')options=state.records.filter(x=>x.type==='product').map(x=>[x.id,`${x.name} · ${x.unit}`]);if(f.type==='diet')options=state.records.filter(x=>x.type==='diets').map(x=>[x.id,`${x.room} · ${x.initials} · ${x.localRef}`]);const value=r[f.key]??'',id=`field-${f.key}`,attrs=`id="${id}" name="${f.key}" ${f.required?'required':''}`;let control;
 if(['select','category','product','diet'].includes(f.type))control=`<select ${attrs}><option value="">Choose…</option>${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${value===v?'selected':''}>${esc(t)}</option>`;}).join('')}</select>`;
 else if(f.type==='textarea')control=`<textarea ${attrs} maxlength="3000">${esc(value)}</textarea>`;
 else if(f.type==='photo')control=`<input ${attrs} type="file" accept="image/jpeg,image/png,image/webp"><span class="help">JPEG, PNG or WebP, up to 4 MB. Leave blank to keep current photo.</span>${safePhoto(value)?`<img class="photo" src="${value}" alt="Current ${esc(f.label)}"><label class="check"><input type="checkbox" name="remove-${f.key}">Remove this photo</label>`:''}`;
 else {const numeric=['integer','positive','decimal','temperature'].includes(f.type);control=`<input ${attrs} type="${numeric?'number':f.type==='initials'?'text':f.type}" value="${esc(value)}" ${numeric?`step="${f.type==='integer'?'1':'any'}" ${f.type==='temperature'?'':'min="0"'}`:''} ${f.type==='initials'?'pattern="[A-Za-z]{1,3}" maxlength="3" title="Use 1–3 letters only"':''} ${f.type==='text'?'maxlength="1000"':''}>`;}
 return `<div class="${f.type==='textarea'?'wide':''}"><label for="${id}">${esc(f.label)}${f.required?' *':''}</label>${control}</div>`;
}
function guideForm(form,type){
 const hint=document.createElement('p');hint.className='help guided-help';hint.textContent='Guided entry: selections advance automatically. Press Enter after typing to move on; use Ctrl+Enter in notes. Tab skips optional fields. Review, then save.';form.prepend(hint);
 const advance=field=>{if(!field.checkValidity()){field.reportValidity();return;}const fields=[...form.querySelectorAll('input:not([type=range]),select,textarea,#save-record')].filter(el=>!el.disabled&&el.type!=='hidden');const next=fields[fields.indexOf(field)+1];if(next){next.focus();if(['text','number'].includes(next.type))next.select();}};
 const keys=type==='cold'?['temperature']:type==='dishwasher'?['wash','rinse']:[];
 for(const key of keys){const input=form.elements.namedItem(key);const wrap=document.createElement('div');wrap.className='temperature-control';input.before(wrap);wrap.append(input);const slider=document.createElement('input');slider.type='range';slider.step='1';slider.setAttribute('aria-label',input.labels[0].textContent+' slider');const status=document.createElement('span');status.className='help';const bounds=document.createElement('span');bounds.className='temperature-bounds';wrap.prepend(slider);wrap.append(status,bounds);
 const sync=()=>{const has=input.value!=='';slider.value=has?input.value:(+slider.min + +slider.max)/2;status.textContent=has?`${input.value} °F`:'No reading entered';slider.setAttribute('aria-valuetext',has?`${input.value} degrees Fahrenheit`:'No reading entered');wrap.classList.toggle('unrecorded',!has);};
 const range=()=>{const freezer=form.elements.namedItem('kind')?.value==='Freezer';const min=type==='dishwasher'?80:freezer?-40:0,max=type==='dishwasher'?220:freezer?40:80;slider.min=input.min=min;slider.max=input.max=max;bounds.textContent=`${min} °F to ${max} °F`;sync();};range();form.elements.namedItem('kind')?.addEventListener('change',range);
 input.addEventListener('input',sync);slider.addEventListener('input',()=>{input.value=slider.value;sync();});slider.addEventListener('change',()=>{input.value=slider.value;sync();});slider.addEventListener('pointerup',()=>{input.value=slider.value;sync();advance(input);});slider.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.value=slider.value;sync();advance(input);}});
 }
 form.addEventListener('change',event=>{if(event.target.matches('select,input[type=file]')&&event.target.value)advance(event.target);});
 form.addEventListener('keydown',event=>{const field=event.target;if(event.key!=='Enter'||event.isComposing||field.tagName==='BUTTON'||field.type==='range'||field.type==='file')return;if(field.tagName==='TEXTAREA'&&!event.ctrlKey)return;event.preventDefault();advance(field);});
 form.querySelector('input,select,textarea')?.focus();
}
function storageForm(form,editing){
 const field=name=>form.elements.namedItem(name),list=document.createElement('datalist');list.id='storage-equipment';field('equipment').setAttribute('list',list.id);field('equipment').autocomplete='off';form.append(list);
 const populate=()=>{list.innerHTML=storageDefaults(state.records,field('date').value).options.map(value=>`<option value="${esc(value)}"></option>`).join('');};populate();
 const apply=defaults=>{for(const key of ['equipment','kind','temperature','target','time'])field(key).value=defaults[key];field('kind').dispatchEvent(new Event('change'));field('temperature').dispatchEvent(new Event('input'));};
 const selectEquipment=()=>{const currentTime=field('time').value;const defaults=storageDefaults(state.records,field('date').value,field('equipment').value);if(defaults.kind){apply({...defaults,time:currentTime});}else{field('kind').value='';field('temperature').value='';field('target').value='';field('kind').dispatchEvent(new Event('change'));field('temperature').dispatchEvent(new Event('input'));}};field('equipment').addEventListener('change',selectEquipment);field('equipment').addEventListener('input',()=>{if(storageDefaults(state.records,field('date').value,field('equipment').value).kind)selectEquipment();});
 field('kind').addEventListener('change',()=>{field('target').value=field('kind').value==='Freezer'?'0 °F':field('kind').value==='Refrigerator'?'35 °F':'';});
 field('date').addEventListener('change',()=>{if(!field('date').checkValidity())return;populate();if(!editing)apply(storageDefaults(state.records,field('date').value));});
}
function editor(type,id){const schema=schemas[type],r=id?state.records.find(x=>x.id===id):{type,date:selectedDate,review:'Pending',family:'Not yet verified',status:'Open',...(type==='cold'?storageDefaults(state.records,selectedDate):{})};$('#dialog-content').innerHTML=`<div class="panel-head">${heading(`${id?'Edit':'Add'} ${schema.title.toLowerCase()}`,schema.source)}<button id="close-editor" aria-label="Close form">✕</button></div><p class="help">${esc(schema.description)} Required fields are marked *. ${type==='cold'?'':'No child names in any field.'}</p><form id="record-form"><div class="form-grid">${fieldHTML({key:'date',label:type==='diets'?'Effective from':'Record date',type:'date',required:true},r)}${schema.fields.map(f=>fieldHTML(f,r)).join('')}${fieldHTML({key:'operator',label:'Staff initials recording this entry',type:'initials',required:true},r)}${id?fieldHTML({key:'editReason',label:'Reason for correction',type:'text',required:true},{}):''}</div><div id="form-errors" role="alert"></div><div class="form-actions"><button type="button" id="cancel-editor">Cancel</button><button class="primary" id="save-record">Save record</button></div></form>`;
 const dialog=$('#editor');dialog.showModal();if(type==='cold')storageForm($('#record-form'),!!id);guideForm($('#record-form'),type);$('#close-editor').onclick=$('#cancel-editor').onclick=()=>dialog.close();
 $('#record-form').onsubmit=async event=>{event.preventDefault();const button=$('#save-record');button.disabled=true;try{const data=new FormData(event.target),record={...(id?r:{}),id:r.id||crypto.randomUUID(),type,date:data.get('date'),operator:String(data.get('operator')).toUpperCase(),role:role(),updatedAt:new Date().toISOString()};for(const f of schema.fields){if(f.type==='photo'){const file=data.get(f.key);record[f.key]=data.get(`remove-${f.key}`)?'':r[f.key]||'';if(file?.size){if(file.size>4*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Photos must be JPEG, PNG or WebP and no larger than 4 MB.');record[f.key]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Photo could not be read.'));reader.readAsDataURL(file);});}}else record[f.key]=String(data.get(f.key)||'').trim();}
 const errors=validateRecord(record,state.records);if(errors.length)throw Error(errors.join('\n'));
 const next=structuredClone(state),index=next.records.findIndex(x=>x.id===record.id);if(index<0)next.records.push(record);else next.records[index]=record;
 await commit(next,id?`Corrected ${type}: ${data.get('editReason')}`:`Added ${type}`,record.id,id?r:null);dialog.close();render();}catch(error){$('#form-errors').className='error';$('#form-errors').textContent=error.message;}finally{button.disabled=false;}};
}
function renderDebug(){return head('Generate sample records','Build a repeatable, normal-operation scenario for testing reports.','reports')+`<section class="panel"><h2>Date range</h2><p>Weekdays only, up to 31 calendar days per generation. Includes six rooms, reviewed meal counts, daily menus and component production for ages 1, 2 and 3–5, dietary attendance, inventory receiving/use, temperatures, sanitation, cleaning and plate waste. Readings vary slightly within the stated sample targets. No corrective actions are generated.</p><p class="help">Fictional evidence references and equipment targets are for software testing, not proof of regulatory compliance. Infant samples use the birth–5-month formula-feeding scenario; no cooling batches or incidents. Product photos and real supporting documents are not fabricated.</p><p class="help">Generating replaces only the Debug dataset. Admin and Lead Cook records stay separate. Switch roles to return to them.</p><p>${state.records.length} sample records available.</p><button data-nav="reports">Open sample reports ↗</button></section>`;}
$('#role').addEventListener('change',async()=>{const nextRole=role();if(menuDirty||$('#editor').open){$('#role').value=activeRole;notify('Save or close the open form before switching workspaces.');return;}$('#role').disabled=true;try{const key=nextRole==='Debug'?'debug-state':'state';const loaded=await load(key);stateKey=key;state=loaded;activeRole=nextRole;section=nextRole==='Debug'?'debug':'today';$('#print-area').innerHTML='';render();}catch(error){$('#role').value=activeRole;notify(error.message);}finally{$('#role').disabled=false;}});
function bindView(){
 const demo=$('#demo-form');if(demo)demo.onsubmit=async event=>{event.preventDefault();if(menuDirty||$('#editor').open){notify('Save or close the open form before generating sample data.');return;}const button=demo.querySelector('button');button.disabled=true;$('#role').disabled=true;try{const values=Object.fromEntries(new FormData(demo)),generated=generateDemo(values.from,values.through,values);generated.state.revision=state.revision;await commit(generated.state,`Generated synthetic records for ${values.from} through ${values.through}`);selectedDate=values.through;week=monday(selectedDate);render();$('#demo-status').textContent=`Ready: ${generated.days} weekdays, ${state.records.length} validated sample records. Open sample reports to print the date range.`;}catch(error){$('#demo-status').textContent=error.message;}finally{button.disabled=false;$('#role').disabled=false;}};
 const date=$('#working-date');if(date)date.onchange=()=>{if(date.value){selectedDate=date.value;render();}};
 const wf=$('#week');if(wf)wf.onchange=()=>{if(menuDirty&&!confirm('Discard the unsaved menu changes?')){wf.value=week;return;}week=monday(wf.value||selectedDate);menuDirty=false;render();};
 const mf=$('#menu-form');if(mf){mf.oninput=()=>{menuDirty=true;$('#menu-status').textContent='Unsaved changes';};mf.onsubmit=async e=>{e.preventDefault();const b=mf.querySelector('button');b.disabled=true;try{const next=structuredClone(state);const before=next.menus[week];next.menus[week]=encodeMenu(Object.fromEntries(new FormData(mf)));await commit(next,`Saved menu for ${week}`,`menu:${week}`,before);menuDirty=false;render();}catch(err){notify(err.message);b.disabled=false;}};}
 const cf=$('#category-form');if(cf)cf.onsubmit=async e=>{e.preventDefault();const name=String(new FormData(cf).get('category')).trim();if(!name||state.categories.some(c=>c.toLowerCase()===name.toLowerCase()))return notify('Enter a new category name.');try{const next=structuredClone(state);next.categories.push(name);await commit(next,'Added dietary category');render();}catch(err){notify(err.message);}};
 if($('#export'))$('#export').onclick=()=>download(`spruce-backup-${localDate()}.json`,JSON.stringify(state,null,2),'application/json');
 if($('#import'))$('#import').onchange=previewRestore;
 if($('#report-form'))$('#report-form').onsubmit=previewReport;
}
function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function previewRestore(event){try{const file=event.target.files[0];if(!file)return;if(file.size>80*1024*1024)throw Error('Backup exceeds the 80 MB prototype import limit.');const incoming=validateBackup(JSON.parse(await file.text()));$('#restore-preview').innerHTML=`<div class="banner warning"><b>Restore preview</b><p>${incoming.records.length} records · ${Object.keys(incoming.menus).length} menus · ${incoming.history.length} revisions. This will replace ${state.records.length} current records. Export the current data first.</p><button id="restore-confirm">Replace local data with this backup</button></div>`;$('#restore-confirm').onclick=async()=>{if(!confirm('Replace this browser’s current records with the previewed backup?'))return;try{incoming.revision=state.revision;await commit(incoming,'Restored full backup');render();}catch(err){notify(err.message);}};}catch(error){notify(error.message);}}
function reportSheets(title,fields,rows,range,rule=''){
 const bands=[];for(let i=0;i<fields.length;i+=5)bands.push(fields.slice(i,i+5));
 return bands.map((band,index)=>`<section class="report-sheet"><table class="sheet-table"><colgroup><col style="width:5%"><col style="width:12%">${band.map(()=>'<col>').join('')}</colgroup><thead><tr><th class="sheet-title" colspan="${band.length+2}">CCS Alaska · ${esc(title)}${bands.length>1?` · Sheet ${index+1} of ${bands.length}`:''}</th></tr><tr><th class="sheet-subtitle" colspan="${band.length+2}">${esc(range.from)} – ${esc(range.to)} · ${rows.length} records${role()==='Debug'?' · SAMPLE / NOT FOR REIMBURSEMENT':''}<br>${esc(rule)}</th></tr><tr><th class="sheet-row-number" scope="col">Row</th><th scope="col">Date</th>${band.map(f=>`<th scope="col">${esc(f.label)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><th scope="row">${i+1}</th><td>${esc(r.date)}</td>${band.map(f=>{const value=r[f.key];return `<td class="${['integer','positive','decimal','temperature'].includes(f.type)?'sheet-number':''}">${f.type==='photo'?(safePhoto(value)?`<img class="photo" src="${value}" alt="${esc(f.label)}">`:'—'):esc(value===undefined||value===''?'—':schemas[r.type]?resolve(r,f.key,value):value)}</td>`;}).join('')}</tr>`).join('')}</tbody></table><div class="sheet-signoff">Reviewed by: ____________________ Date: ____________ <span>Matching row numbers identify the same record across sheets.</span></div></section>`).join('');
}
function previewReport(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.target));if(values.from>values.to)return notify('Start date must be on or before end date.');const list=state.records.filter(r=>(values.type==='all'||r.type===values.type)&&(r.type==='diets'?r.date<=values.to&&(!r.end||r.end>=values.from):r.type==='product'?r.date<=values.to:r.date>=values.from&&r.date<=values.to)).sort((a,b)=>a.date.localeCompare(b.date));
 let html=`${role()==='Debug'?'<h1>SAMPLE — DEBUG DATA — NOT FOR REIMBURSEMENT</h1>':''}<h1>CCS Alaska · Kitchen record packet</h1><p>${esc(values.from)} through ${esc(values.to)} inclusive · Prepared ${esc(new Date().toLocaleString())}</p><p>Prototype record export · ${esc(values.type==='all'?'All records':values.type)} · Staff review required. Initials and dietary details are confidential. Current record versions shown.</p>`;
 const counts=list.filter(r=>r.type==='counts');if(counts.length){html+='<h2>Room meal reconciliation</h2><p>Reimbursable totals include reviewed records only. Missing room/meal records are not zero. Attendance is meal-specific and must not be summed as unique daily attendance.</p><table><thead><tr>'+['Date','Room','Meal','Enrolled','Present','Requested','Prepared','POS','Reimbursable','Adults','Review'].map(v=>`<th>${v}</th>`).join('')+'</tr></thead><tbody>'+counts.map(r=>`<tr>${[r.date,r.room,r.meal,r.enrolled,r.attendance,r.requested,r.prepared,r.served,r.review==='Reviewed'?r.reimbursable:'Pending',+r.staff + +r.volunteers + +r.visitors,r.review].map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')+'</tbody><tfoot><tr><th colspan="5">Meal-event totals</th>'+['requested','prepared','served'].map(k=>`<td>${counts.reduce((sum,r)=>sum+Number(r[k]||0),0)}</td>`).join('')+`<td>${counts.filter(r=>r.review==='Reviewed').reduce((sum,r)=>sum+Number(r.reimbursable||0),0)}</td><td>${counts.reduce((sum,r)=>sum+Number(r.staff||0)+Number(r.volunteers||0)+Number(r.visitors||0),0)}</td><td>Reviewed claims only</td></tr></tfoot></table>`;}
 if(['all','menus'].includes(values.type)){for(const [wk,raw] of Object.entries(state.menus).sort()){const menu=decodeMenu(raw),days=Array.from({length:5},(_,i)=>{const d=new Date(wk+'T12:00:00');d.setDate(d.getDate()+i);return [i,localDate(d)];}).filter(([,d])=>d>=values.from&&d<=values.to);if(days.length)html+=`<h2>Menu · week of ${esc(wk)}</h2><table><thead><tr><th>Date</th>${meals.map(m=>`<th>${m}</th>`).join('')}</tr></thead><tbody>${days.map(([i,d])=>`<tr><th>${d}</th>${meals.map(m=>`<td>${esc(menu[`${i}.${m.toLowerCase()}`]||'Not entered')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}}
 if(values.type==='history'){const history=state.history.filter(h=>h.date>=values.from&&h.date<=values.to).map(h=>({...h,before:JSON.stringify(h.before,null,2)}));html+=reportSheets('Revision history',[{key:'at',label:'Saved at'},{key:'description',label:'Change'},{key:'role',label:'Role'},{key:'recordId',label:'Record ID'},{key:'before',label:'Previous values'}],history,values);}
 for(const [type,s] of Object.entries(schemas)){const rs=list.filter(r=>r.type===type);if(rs.length)html+=reportSheets(s.title,[...s.fields,{key:'operator',label:'Staff initials'},{key:'role',label:'Working role'},{key:'updatedAt',label:'Last saved'},{key:'id',label:'Record ID'}],rs,values,sources[s.source].rule);}
 html=html.replaceAll('<table>','<table class="sheet-table">');
 $('#print-area').innerHTML=html;$('#report-preview').innerHTML=`<p class="help">${list.length} matching records. Dietary plans overlapping the range and products created by the end date are included as reference records.</p><button id="print-button" class="primary">Print / save PDF</button><details class="record" open><summary>Packet preview</summary>${html}</details>`;$('#print-button').onclick=()=>window.print();
}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(menuDirty&&(b.dataset.new||b.dataset.edit)){notify('Save your menu changes before opening a production record.');return;}if(b.dataset.nav){if(menuDirty&&!confirm('Discard unsaved menu changes?'))return;menuDirty=false;section=b.dataset.nav;render();}if(b.dataset.new)editor(b.dataset.new);if(b.dataset.edit){const r=state.records.find(r=>r.id===b.dataset.edit);editor(r.type,r.id);}if(b.dataset.logTab){logType=b.dataset.logTab;render();}if(b.dataset.inventoryTab){inventoryType=b.dataset.inventoryTab;render();}if(b.dataset.dietTab){dietType=b.dataset.dietTab;render();}if(b.dataset.goWaste){section='logs';logType='waste';render();}});
window.addEventListener('beforeunload',e=>{if(menuDirty||$('#editor').open){e.preventDefault();e.returnValue='';}});
function connection(){const controlled=!!navigator.serviceWorker?.controller;$('#connection').textContent=controlled?(navigator.onLine?'Offline ready · saved locally':'Offline · saved locally'):'Local browser · preparing offline';}
window.addEventListener('online',connection);window.addEventListener('offline',connection);
try{db=await new Promise((resolve,reject)=>{const request=indexedDB.open('spruce-kitchen',1);request.onupgradeneeded=()=>request.result.createObjectStore('data');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});state=await load();render();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(connection).catch(()=>{$('#connection').textContent='Local storage · offline cache unavailable';});navigator.serviceWorker.addEventListener('controllerchange',connection);}connection();}catch(error){$('#main').innerHTML=`<div class="error">Local database could not open. Enable browser storage and reload. ${esc(error.message)}</div>`;}














