'use strict';
function renderComplianceGuide(){
  const source=(url,label)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
  const breakfast='https://www.fna.usda.gov/cacfp/nutrition-standards/breakfast-meal-pattern';
  const lunch='https://foodbuyingguide.fns.usda.gov/Content/TablesFBG/Chart4B_FBG_CACFP_Meal_Pattern_for_Children_and_Adults_Lunch_and_Supper.pdf';
  const snack='https://www.fna.usda.gov/cacfp/nutrition-standards/snack-meal-pattern';
  const infant='https://www.fna.usda.gov/cacfp/nutrition-standards/infant-meal-patterns';
  const table=(title,note,rows,url)=>`<section class="panel"><h2>${title}</h2><p>${note}</p><div class="guide-table-wrap" tabindex="0" role="region" aria-label="${title} portions"><table class="guide-table"><caption>Minimum per child, per service</caption><thead><tr><th scope="col">Component</th><th scope="col">Ages 1–2</th><th scope="col">Ages 3–5</th><th scope="col">Ages 6–12</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r[0]}</th>${r.slice(1).map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>${source(url,'USDA '+title+' pattern')}</p></section>`;
  $('#content').innerHTML=`<div class="compliance-guide"><div class="page-title"><div><div class="eyebrow">CACFP QUICK REFERENCE</div><h1>Compliance Guide</h1><p>Meal components, minimum portions, and substitutions.</p></div><span class="badge">Snapshot · September 24, 2026</span></div>
  <div class="panel"><h2>Use this snapshot</h2><p>A planning reference for child care, including Head Start and Early Head Start. This saved guide does not update automatically or certify a menu. Confirm current requirements and required records with your sponsor or state agency. Portions below are minimums, not maximums.</p><p><a href="#guide-children">Child portions</a> · <a href="#guide-rules">Component rules</a> · <a href="#guide-infants">Infants</a> · <a href="#guide-substitutions">Substitutions</a></p></div>
  <div id="guide-children"><h2>Children ages 1–12</h2><p>1 cup = 8 fluid ounces. “oz eq” means ounce equivalent of a creditable component, not necessarily the weight of the finished food. Use the ${source('https://foodbuyingguide.fns.usda.gov/Home/ResourceCenter','USDA Food Buying Guide')} for food-specific crediting and yields.</p>
  ${table('Breakfast','Serve all three components; see the breakfast substitution option below.',[['Fluid milk','½ cup','¾ cup','1 cup'],['Vegetables, fruits, or both','¼ cup','½ cup','½ cup'],['Grains','½ oz eq','½ oz eq','1 oz eq']],breakfast)}
  ${table('Lunch / supper','Serve all five components.',[['Fluid milk','½ cup','¾ cup','1 cup'],['Meat / meat alternate','1 oz eq','1½ oz eq','2 oz eq'],['Vegetables','⅛ cup','¼ cup','½ cup'],['Fruits','⅛ cup','¼ cup','¼ cup'],['Grains','½ oz eq','½ oz eq','1 oz eq']],lunch)}
  ${table('Snack','Choose two different components. Milk and juice alone do not make a reimbursable snack.',[['Fluid milk','½ cup','½ cup','1 cup'],['Meat / meat alternate','½ oz eq','½ oz eq','1 oz eq'],['Vegetables','½ cup','½ cup','¾ cup'],['Fruits','½ cup','½ cup','¾ cup'],['Grains','½ oz eq','½ oz eq','1 oz eq']],snack)}</div>
  <section class="panel" id="guide-rules"><h2>Component rules to remember</h2><h3>Milk · updated June 8, 2026</h3><p>Age 1: unflavored whole milk. Ages 2–5: unflavored whole, 2%, 1%, or fat-free milk. Ages 6 and older: those same fat levels, flavored or unflavored. The 2026 rule expands the choices for ages two and older; older meal-chart footnotes may still show the previous limits. Follow your facility’s chosen milk policy.</p><p>${source('https://www.fna.usda.gov/cn/fr-050826','USDA 2026 milk rule')}</p><h3>Grains, sugar, and juice</h3><ul><li>Include at least one whole grain-rich serving each day. Grain-based desserts do not count toward grains.</li><li>Breakfast cereal: no more than 6 g added sugars per dry ounce. Yogurt: no more than 12 g added sugars per 6 oz (2 g per oz). These added-sugar limits took effect October 1, 2025.</li><li>Only pasteurized, full-strength juice credits; limit it to one meal or snack per day.</li></ul><p>${source(snack,'USDA component notes')}</p></section>
  <section class="panel" id="guide-infants"><h2>Infants · birth through 11 months</h2><p>Use the infant pattern, not the child tables. Feed according to developmental readiness; introduce required solid components when ready. Formula and infant cereal must be iron-fortified. Do not serve juice.</p><h3>Birth–5 months</h3><p>Each meal or snack: 4–6 fl oz breastmilk or formula.</p><h3>6–11 months</h3><p>Breakfast, lunch, supper: 6–8 fl oz breastmilk/formula; 0–½ oz eq infant cereal OR 0–4 tbsp meat, fish, poultry, whole egg, cooked dry beans/peas/lentils OR 0–2 oz cheese OR 0–4 oz cottage cheese (volume) or yogurt (weight); plus 0–2 tbsp vegetables/fruits.</p><p>Snack: 2–4 fl oz breastmilk/formula; 0–½ oz eq bread or infant cereal OR 0–¼ oz eq crackers or ready-to-eat cereal; plus 0–2 tbsp vegetables/fruits.</p><p>Ranges beginning at zero reflect readiness, not permission to omit solids once ready. Some breastfed infants take less than the minimum; offer more later if they will drink it. Review the full chart’s grain and sugar requirements.</p><p>${source(infant,'USDA infant pattern and footnotes')}</p></section>
  <section class="panel" id="guide-substitutions"><h2>Substitutions & meal modifications</h2><h3>Breakfast grains</h3><p>Meat/meat alternates may replace the entire grain requirement at breakfast up to three times per week. Substitute equal ounce equivalents.</p><p>${source(breakfast,'USDA breakfast substitution')}</p><h3>Preferences and milk substitutes</h3><p>Preference-based swaps must still provide creditable components and required portions. For a nondairy milk substitute, obtain a written request identifying the reason and verify that the product meets all federal nutrient-equivalence requirements; a plant-based name alone is not enough. Lactose-free dairy milk meeting the age requirements is a creditable milk option.</p><h3>Disability-related needs</h3><p>Provide reasonable meal modifications at no extra charge. When a modification falls outside the meal pattern, obtain a medical statement from a state-licensed healthcare professional authorized to prescribe or a registered dietitian. USDA does not require that statement for modifications within the meal pattern, though local documentation procedures may apply. Coordinate accommodations promptly rather than delaying while awaiting paperwork.</p><p>${source('https://www.cdss.ca.gov/cacfp/resources/meal-modifications-in-the-cacfp','State-agency explanation of federal modification rules')} · ${source('https://fns-prod.azureedge.us/cn/requirement-accept-medical-statements-registered-dietitians','USDA medical-statement update')}</p><p>Record the actual substitution and portions on your facility’s meal records. Keep individual medical statements in your approved confidential system.</p></section></div>`;
}
