'use strict';
function validDeliveries(deliveries){return deliveries===undefined||(Array.isArray(deliveries)&&deliveries.every(d=>d&&typeof d.id==='string'&&typeof d.supplier==='string'&&typeof d.date==='string'&&['draft','posted'].includes(d.status)&&Array.isArray(d.items)&&d.items.every(i=>i&&typeof i.name==='string'&&typeof i.unit==='string'&&Number.isFinite(+i.quantity)&&+i.quantity>=0&&['accepted','hold','rejected'].includes(i.decision))))}
function planDeliveryStock(delivery,inventory){
  if(delivery.status==='posted')throw Error('This delivery has already been posted. Its stock cannot be added again.');
  const result=structuredClone(inventory);let added=0;const updated=new Set();
  for(const line of delivery.items){
    if(!line.name.trim()||!line.unit.trim()||String(line.quantity).trim()===''||!Number.isFinite(+line.quantity)||+line.quantity<0)throw Error('Each item needs a name, unit, and received quantity of zero or more.');
    if(!['accepted','hold','rejected'].includes(line.decision))throw Error('Choose a receiving decision for every item.');
    if(line.decision!=='accepted'||+line.quantity===0)continue;
    const name=resolveInventoryAlias(line.name),key=receiptItemKey({name,unit:line.unit});
    const matches=result.filter(item=>receiptItemKey(item)===key||aliasedInventoryKey(item)===key);
    if(matches.length>1)throw Error(`Multiple inventory items match ${name}. Make their names or units unique before posting.`);
    const reference={id:delivery.id,supplier:delivery.supplier,date:delivery.date,invoice:delivery.invoice};
    if(matches.length){const existing=matches[0],stock=Number(existing.quantity);if(!Number.isFinite(stock)||stock<0)throw Error(`Correct the current stock quantity for ${name}.`);existing.quantity=String(Number((stock+Number(line.quantity)).toFixed(6)));existing.name=name;existing.lastDelivery=reference;if(inventory.some(i=>i.id===existing.id))updated.add(existing.id)}
    else{result.push({id:crypto.randomUUID(),name,quantity:String(+line.quantity),unit:line.unit.trim(),minimum:'',expires:line.expires||'',location:line.storage||'',lastDelivery:reference});added++}
  }
  return {inventory:result,added,updated:updated.size};
}
function renderDeliveries(){const deliveries=[...(db.deliveries||[])].sort((a,b)=>b.date.localeCompare(a.date)),drafts=deliveries.filter(d=>d.status==='draft');
  $('#content').innerHTML=`<div class="page-title"><div><div class="eyebrow">KITCHEN RECEIVING</div><h1>Receiving deliveries</h1><p>Record what arrived, check its condition, and put accepted items into stock.</p></div><button class="primary" id="newDelivery">+ Receive delivery</button></div><div class="stats"><div class="stat"><strong>${drafts.length}</strong><span>Awaiting posting</span></div><div class="stat"><strong>${deliveries.length-drafts.length}</strong><span>Posted deliveries</span></div><div class="stat"><strong>${deliveries.reduce((n,d)=>n+d.items.filter(i=>i.decision==='hold'||i.decision==='rejected').length,0)}</strong><span>Held or rejected lines</span></div></div>${[['draft','Awaiting review'],['posted','Delivery history']].map(([status,title])=>`<section class="panel"><h2>${title}</h2>${deliveries.some(d=>d.status===status)?deliveries.filter(d=>d.status===status).map(d=>`<article class="record"><div><strong>${esc(d.supplier)}</strong><p>${esc(d.date)} · ${d.items.length} items${d.invoice?' · Invoice '+esc(d.invoice):''}</p><span class="badge ${status==='posted'?'green':'yellow'}">${status==='posted'?'Posted to inventory':'Draft · stock unchanged'}</span></div><button data-delivery="${esc(d.id)}">${status==='posted'?'View delivery':'Review delivery'}</button></article>`).join(''):'<div class="empty">'+(status==='draft'?'No deliveries waiting for review.':'Posted deliveries will appear here.')+'</div>'}</section>`).join('')}`;
  $('#newDelivery').onclick=()=>openDelivery();document.querySelectorAll('[data-delivery]').forEach(b=>b.onclick=()=>openDelivery(b.dataset.delivery));
}
function openDelivery(id){const saved=(db.deliveries||[]).find(d=>d.id===id),posted=saved?.status==='posted';let items=structuredClone(saved?.items||[{name:'',quantity:'1',ordered:'',unit:'each',temperature:'',decision:'accepted',expires:'',storage:'',notes:''}]),submitting=false;
  const dialog=document.createElement('dialog');dialog.className='delivery-dialog';dialog.setAttribute('aria-labelledby','deliveryTitle');
  dialog.innerHTML=`<form><div class="section-head"><h2 id="deliveryTitle">${posted?'Delivery record':'Receive a delivery'}</h2><button type="button" data-close aria-label="Close delivery">×</button></div>${posted?'<div class="note">Posted to inventory. This record is read-only to prevent adding the stock twice. New items may still need label photos in Inventory.</div>':''}<fieldset ${posted?'disabled':''}><h3>Delivery details</h3><div class="delivery-fields"><label class="field">Supplier<input name="supplier" required value="${esc(saved?.supplier||'')}"></label><label class="field">Received date<input name="date" type="date" required value="${esc(saved?.date||selected)}"></label><label class="field">Invoice / delivery number<input name="invoice" value="${esc(saved?.invoice||'')}"></label><label class="field">Received by<input name="receiver" required value="${esc(saved?.receiver||'')}"></label></div><h3>Items & receiving checks</h3><p class="menu-hint">Record actual temperatures in °F where relevant and follow your facility’s receiving procedures. Only accepted quantities enter inventory. Held and rejected items stay out of stock.</p><div data-items></div>${posted?'':'<button type="button" data-add-item>+ Add item</button>'}<h3>Paperwork & discrepancies</h3><label class="field">Delivery notes<textarea name="notes" placeholder="Shortages, damaged packages, substitutions, or follow-up needed">${esc(saved?.notes||'')}</textarea></label><label class="field">Invoice or delivery document (PDF or image, up to 2 MB)<input type="file" name="document" accept="application/pdf,image/png,image/jpeg,image/webp"></label>${saved?.file?'<p>Existing document is kept unless replaced.</p>':''}</fieldset>${saved?.file?'<button type="button" data-download>Download delivery document</button>':''}<p data-error role="alert"></p><div class="menu-confirm-actions"><button type="button" data-close>Close</button>${posted?'':'<button type="submit" name="action" value="draft">Save draft</button><button type="submit" class="primary" name="action" value="post">Post & update stock</button>'}</div></form>`;
  function renderItems(){dialog.querySelector('[data-items]').innerHTML=items.map((item,i)=>`<section class="delivery-item"><div class="section-head"><h3>Item ${i+1}</h3>${posted?'':`<button type="button" data-remove="${i}" aria-label="Remove item ${i+1}">Remove</button>`}</div><div class="delivery-fields">${posted?'':`<label class="field">Choose inventory item<select data-choose="${i}"><option value="">Select an existing item or enter a name</option>${db.inventory.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} (${esc(r.unit)})</option>`).join('')}</select></label>`}${[['name','Item name','text'],['ordered','Ordered quantity (optional)','number'],['quantity','Received quantity','number'],['unit','Unit','text'],['temperature','Receiving temperature (°F)','number'],['expires','Expiration / use-by','date'],['storage','Storage location','text']].map(([key,label,type])=>`<label class="field">${label}<input type="${type}" data-item="${i}" data-field="${key}" value="${esc(item[key]??'')}" ${['name','quantity','unit'].includes(key)?'required':''} ${type==='number'?`step="any" ${key==='temperature'?'':'min="0"'}`:''}></label>`).join('')}<label class="field">Receiving decision<select data-item="${i}" data-field="decision">${[['accepted','Accepted'],['hold','On hold'],['rejected','Rejected']].map(([value,label])=>`<option value="${value}" ${item.decision===value?'selected':''}>${label}</option>`).join('')}</select></label></div><label class="field">Condition / discrepancy notes<textarea data-item="${i}" data-field="notes">${esc(item.notes||'')}</textarea></label></section>`).join('');
    dialog.querySelectorAll('[data-item]').forEach(input=>input.oninput=()=>{items[+input.dataset.item][input.dataset.field]=input.value});
    dialog.querySelectorAll('[data-choose]').forEach(select=>select.onchange=()=>{const stock=db.inventory.find(r=>r.id===select.value);if(stock){Object.assign(items[+select.dataset.choose],{name:stock.name,unit:stock.unit,storage:stock.location||''});renderItems()}});
    dialog.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{items.splice(+button.dataset.remove,1);renderItems()});
  }
  renderItems();if(!posted)dialog.querySelector('[data-add-item]').onclick=()=>{items.push({name:'',quantity:'1',ordered:'',unit:'each',temperature:'',decision:'accepted',expires:'',storage:'',notes:''});renderItems()};
  dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!submitting)dialog.close()});dialog.oncancel=event=>{if(submitting)event.preventDefault()};dialog.onclose=()=>dialog.remove();
  if(saved?.file)dialog.querySelector('[data-download]').onclick=()=>download(saved.file.data,saved.file.name);
  dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();if(posted||submitting)return;submitting=true;const buttons=dialog.querySelectorAll('button[type="submit"]');buttons.forEach(b=>b.disabled=true);
    try{const form=new FormData(event.target),supplier=String(form.get('supplier')||'').trim(),receiver=String(form.get('receiver')||'').trim(),date=String(form.get('date')||'');if(!supplier||!receiver||!date)throw Error('Enter the supplier, date, and receiver.');if(!items.length)throw Error('Add at least one delivered item.');
      const delivery={...saved,id:id||crypto.randomUUID(),supplier,receiver,date,invoice:String(form.get('invoice')||'').trim(),notes:String(form.get('notes')||'').trim(),items:structuredClone(items),status:'draft'};
      const plan=planDeliveryStock(delivery,db.inventory);const file=form.get('document');
      if(file?.size){if(file.size>2*1024*1024||!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PDF, PNG, JPEG, or WebP document under 2 MB.');delivery.file={name:file.name,data:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read the delivery document.'));reader.readAsDataURL(file)})}}
      const post=event.submitter?.value==='post',oldDeliveries=db.deliveries,oldInventory=db.inventory;
      if(post){delivery.status='posted';delivery.postedAt=today();db.inventory=plan.inventory}
      db.deliveries=[...(db.deliveries||[]).filter(d=>d.id!==delivery.id),delivery];
      if(!save()){db.deliveries=oldDeliveries;db.inventory=oldInventory;throw Error('Could not save the delivery. Storage may be full. Your inventory was not changed.')}
      dialog.close();render();notify(post?`Delivery posted: ${plan.added} new items, ${plan.updated} stock quantities updated.`:'Delivery draft saved; inventory unchanged');
    }catch(error){dialog.querySelector('[data-error]').textContent=error.message}finally{submitting=false;buttons.forEach(b=>b.disabled=false)}
  };
  document.body.append(dialog);dialog.showModal();
}
