'use strict';
const suppliedShoppingRoute={name:'Fairview Center → Carrs → Fred Meyer → Fairview Center',url:'https://maps.app.goo.gl/xpiiSi13LxtZc2Fh8?g_st=ac',miles:35.1,verified:'2026-09-23'};
function validMapsLink(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password&&(url.hostname==='maps.app.goo.gl'||url.hostname==='maps.google.com'||((url.hostname==='google.com'||url.hostname==='www.google.com')&&url.pathname.startsWith('/maps'))||(url.hostname==='goo.gl'&&url.pathname.startsWith('/maps')))}catch{return false}}
function knownShoppingRoute(value){try{return new URL(value).hostname==='maps.app.goo.gl'&&new URL(value).pathname==='/xpiiSi13LxtZc2Fh8'}catch{return false}}
function validMileageRoutes(routes){return routes===undefined||(Array.isArray(routes)&&routes.every(r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.name.trim()&&validMapsLink(r.url)&&Number.isFinite(+r.miles)&&+r.miles>0)&&new Set(routes.map(r=>r.id)).size===routes.length)}
function calculateRouteEnd(start,miles){if(String(start).trim()===''||!Number.isFinite(+start)||+start<0||String(miles).trim()===''||!Number.isFinite(+miles)||+miles<=0)throw Error('Enter a starting odometer of zero or more and route miles greater than zero.');const end=Math.round((+start+ +miles)*1000)/1000;if(!Number.isFinite(end))throw Error('These values are too large.');return end}
function mileageRouteLibrary(){const routes=db.mileageRoutes||[];return `<section class="panel"><div class="section-head"><h2>Saved routes</h2><button type="button" id="addMileageRoute">+ Save route</button></div><p>Save a Maps link and its distance once. Use the route and your starting odometer to log each trip.</p>${routes.length?routes.map(route=>`<article class="record"><div><strong>${esc(route.name)}</strong><p>${Number(route.miles).toFixed(1)} miles · <a href="${esc(route.url)}" target="_blank" rel="noopener noreferrer">Open Maps ↗</a></p></div><div class="record-actions"><button data-trip-route="${esc(route.id)}">Log trip</button><button data-edit-route="${esc(route.id)}">Edit route</button></div></article>`).join(''):'<p class="empty">No saved routes yet. Add your first route or save one while logging a trip.</p>'}</section>`}
function bindMileageRoutes(){$('#addMileageRoute').onclick=()=>openMileageRouteEditor();document.querySelectorAll('[data-edit-route]').forEach(b=>b.onclick=()=>openMileageRouteEditor(b.dataset.editRoute));document.querySelectorAll('[data-trip-route]').forEach(b=>b.onclick=()=>openMileageTrip(null,b.dataset.tripRoute))}
function routeInputs(route={}){return `<label class="field">Google Maps link<input name="routeUrl" type="url" required value="${esc(route.url||'')}" placeholder="https://maps.app.goo.gl/…"></label><a data-open-map target="_blank" rel="noopener noreferrer" hidden>Open route in Maps ↗</a><label class="field">Route name<input name="routeName" required value="${esc(route.name||'')}" placeholder="Kitchen → store → kitchen"></label><label class="field">Route miles (whole trip)<input name="routeMiles" type="number" min="0.001" step="any" required value="${esc(route.miles??'')}"></label><p class="menu-hint" data-route-help>Open the link and enter its total driving distance once. Include the return journey if it is part of the route. New links do not automatically supply live mileage.</p>`}
function bindRouteInputs(dialog,onChange=()=>{}){const link=dialog.querySelector('[name="routeUrl"]'),name=dialog.querySelector('[name="routeName"]'),miles=dialog.querySelector('[name="routeMiles"]'),open=dialog.querySelector('[data-open-map]');
  const update=()=>{open.hidden=!validMapsLink(link.value);if(!open.hidden)open.href=link.value.trim();onChange()};
  link.oninput=link.onchange=()=>{if(knownShoppingRoute(link.value)){name.value=suppliedShoppingRoute.name;miles.value=suppliedShoppingRoute.miles;dialog.querySelector('[data-route-help]').textContent='35.1-mile round trip, checked in Google Maps on September 23, 2026. Adjust it if your journey changes.'}update()};
  miles.oninput=onChange;update();
}
function readRouteForm(form,id){const values=new FormData(form),url=String(values.get('routeUrl')||'').trim(),name=String(values.get('routeName')||'').trim(),miles=+values.get('routeMiles');if(!validMapsLink(url))throw Error('Enter a valid HTTPS Google Maps link.');if(!name||!Number.isFinite(miles)||miles<=0)throw Error('Enter a route name and a distance greater than zero.');return {id:id||crypto.randomUUID(),name,url,miles}}
function saveRouteToDatabase(route){db.mileageRoutes=[...(db.mileageRoutes||[]).filter(r=>r.id!==route.id),route]}
function matchingSavedRoute(route,routes=db.mileageRoutes||[]){const normalizeName=value=>value.trim().replace(/\s+/g,' ').toLowerCase();const normalizeLink=value=>{try{return new URL(value.trim()).href}catch{return value.trim()}};return routes.find(saved=>normalizeName(saved.name)===normalizeName(route.name)&&normalizeLink(saved.url)===normalizeLink(route.url)&&Number(saved.miles)===Number(route.miles))}
function openMileageRouteEditor(id){const current=(db.mileageRoutes||[]).find(r=>r.id===id);const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','routeTitle');dialog.innerHTML=`<form><div class="section-head"><h2 id="routeTitle">${id?'Edit':'Save'} route</h2><button type="button" data-close aria-label="Close route editor">×</button></div>${routeInputs(current)}<p class="menu-hint">Route changes apply to future trips. Previously logged mileage stays unchanged.</p><p data-error role="alert"></p><div class="menu-confirm-actions"><button type="submit" class="primary">Save route</button>${id?'<button type="submit" name="saveAsNew" value="true">Save route as new</button>':''}</div></form>`;bindRouteInputs(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{const asNew=e.submitter?.name==='saveAsNew';const route=readRouteForm(e.target,asNew?undefined:id),previous=db.mileageRoutes;if(asNew||!id){const duplicate=matchingSavedRoute(route);if(duplicate)throw Error(`A route with this name, Maps link, and mileage is already saved as “${duplicate.name}”. Change at least one value to save a new route.`)}saveRouteToDatabase(route);if(!save()){db.mileageRoutes=previous;throw Error('Could not save this route on this device.')}dialog.close();render();notify(asNew?'New route saved; original route kept':'Route saved')}catch(error){dialog.querySelector('[data-error]').textContent=error.message}};document.body.append(dialog);dialog.showModal()}
function openMileageTrip(id,initialRouteId){const existing=db.mileage.find(r=>r.id===id),routes=db.mileageRoutes||[];
  // Historical trips retain their own route distance instead of using a changed saved route.
  const isLegacy=!!existing&&!existing.routeUrl;let mode=existing?(isLegacy?'manual':'snapshot'):(initialRouteId||'new');
  const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','tripTitle');dialog.innerHTML=`<form><div class="section-head"><h2 id="tripTitle">${id?'Edit':'Add'} trip</h2><button type="button" data-close aria-label="Close trip editor">×</button></div><label class="field">Trip purpose<input name="tripPurpose" required value="${esc(existing?.name||'Shopping for kitchen supplies')}"></label><label class="field">Trip date<input name="tripDate" type="date" required value="${esc(existing?.date||selected)}"></label><label class="field">Route<select name="routeChoice"><option value="new">New route from a Maps link</option>${existing?`<option value="${isLegacy?'manual':'snapshot'}">This trip’s recorded route</option>`:''}<option value="provided">Fairview shopping round trip · 35.1 mi</option>${routes.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${Number(r.miles).toFixed(1)} mi</option>`).join('')}</select></label><div data-route-fields></div><label class="field">Starting odometer<input name="tripStart" type="number" min="0" step="any" required value="${esc(existing?.start??'')}"></label><div class="note" data-calculation role="status">Enter a starting odometer to calculate the trip.</div><p class="menu-hint">The ending odometer is calculated from the route distance, not measured. Check against your actual odometer; adjust the trip miles if you take a detour.</p><p data-error role="alert"></p><button type="submit" class="primary">Save trip</button></form>`;
  const choice=dialog.querySelector('[name="routeChoice"]'),start=dialog.querySelector('[name="tripStart"]');choice.value=mode;
  const update=()=>{const miles=dialog.querySelector('[name="routeMiles"]').value;try{const end=calculateRouteEnd(start.value,miles);dialog.querySelector('[data-calculation]').textContent=`Trip: ${Number(miles).toFixed(1)} miles · Calculated ending odometer: ${end.toFixed(1)}`}catch{dialog.querySelector('[data-calculation]').textContent='Enter route miles and a starting odometer to calculate the trip.'}};
  function showRoute(){mode=choice.value;let route=mode==='provided'?suppliedShoppingRoute:mode==='snapshot'?{name:existing.route,url:existing.routeUrl,miles:existing.routeMiles??(+existing.end- +existing.start)}:routes.find(r=>r.id===mode);
    if(mode==='manual'){dialog.querySelector('[data-route-fields]').innerHTML=`<label class="field">Route description<input name="routeName" required value="${esc(existing.route)}"></label><label class="field">Trip miles<input name="routeMiles" type="number" min="0.001" step="any" required value="${esc(+existing.end- +existing.start)}"></label>`;dialog.querySelector('[name="routeMiles"]').oninput=update;update();return}
    dialog.querySelector('[data-route-fields]').innerHTML=routeInputs(route)+(mode==='new'||mode==='provided'?'<p class="menu-hint">This route will be saved with your trip for reuse.</p>':'<p class="menu-hint">Changes here affect this trip only. To change the reusable route, use Edit route.</p>');bindRouteInputs(dialog,update);
  }
  choice.onchange=showRoute;start.oninput=update;showRoute();
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{const data=new FormData(e.target),miles=+data.get('routeMiles'),end=calculateRouteEnd(data.get('tripStart'),data.get('routeMiles')),purpose=String(data.get('tripPurpose')||'').trim(),date=String(data.get('tripDate')||'');if(!purpose||!date)throw Error('Enter the trip purpose and date.');
    let route,routeId=mode==='snapshot'?existing.routeId:mode;if(mode!=='manual'){route=readRouteForm(e.target,mode==='new'||mode==='provided'?undefined:routeId);routeId=route.id}
    const record={...existing,id:id||crypto.randomUUID(),name:purpose,date,route:route?.name||String(data.get('routeName')).trim(),routeUrl:route?.url||'',routeId:mode==='manual'?null:routeId,routeMiles:miles,start:String(data.get('tripStart')),end:String(end),calculated:true};
    const oldMileage=db.mileage,oldRoutes=db.mileageRoutes;
    if(mode==='new'||mode==='provided'){const same=(db.mileageRoutes||[]).find(r=>r.url===route.url&&r.name===route.name&&+r.miles===route.miles);if(same)record.routeId=same.id;else saveRouteToDatabase(route)}
    db.mileage=id?db.mileage.map(r=>r.id===id?record:r):[...db.mileage,record];if(!save()){db.mileage=oldMileage;db.mileageRoutes=oldRoutes;throw Error('Could not save this trip on this device.')}
    dialog.close();render();notify('Trip saved; mileage totals updated');
  }catch(error){dialog.querySelector('[data-error]').textContent=error.message}};
  document.body.append(dialog);dialog.showModal();
}
