export const rooms=['EHS Fox Kits','EHS Bear Cubs','HS Fox','HS Bear','HS Puffins','HS Owls'];
export const meals=['Breakfast','Lunch','Snack'];
export const categories=['Allergies','Medical/disability diets','Dairy-free/milk substitute','Texture modifications','Religious/cultural restrictions','Infant formula/breastmilk','Preferences'];
const cfr=s=>`https://www.ecfr.gov/current/title-7/subtitle-B/chapter-II/subchapter-A/part-226/section-226.${s}`;
const hs=s=>`https://headstart.gov/policy/45-cfr-chap-xiii/${s}`;
const ak='https://dec.alaska.gov/commish/regulations/18-aac-31';
export const sources={
 counts:{title:'Meal counts & reconciliation',rule:'7 CFR 226.15(e)(4)–(5); 226.17(b)(9); 226.20(n)',text:'Keep attendance and time-of-service child meal counts separate. Record food-service adult meals separately. Family-style service requires sufficient portions and excludes second meals from claims.',links:[[cfr('15'),'CACFP recordkeeping'],[cfr('20'),'Meal requirements']]},
 menu:{title:'Weekly menu & production',rule:'7 CFR 226.15(e)(10); 226.20(a), (c), (j), (n); 45 CFR 1302.44(a)',text:'Preserve menus, age-specific component quantities, substitutions and production evidence. This text menu does not automatically validate meal crediting.',links:[[cfr('20'),'CACFP meal patterns'],[hs('1302-44-child-nutrition'),'Head Start nutrition']]},
 diets:{title:'Dietary modifications',rule:'45 CFR 1302.44(a)(1); 1302.47(b)(7)(vi); 7 CFR 226.20(g)',text:'Support individual feeding needs and accessible allergy action plans. Initials here do not replace the program’s confidential child identification and posted allergy procedures.',links:[[hs('1302-47-safety-practices'),'Head Start safety'],[cfr('20'),'Meal modifications']]},
 inventory:{title:'Receiving & inventory',rule:'7 CFR 226.15(e)(6), (13); 18 AAC 31.200; 18 AAC 31.234',text:'Retain purchasing evidence and check receiving conditions. Product photographs and the stock ledger are useful supporting tools, not substitutes for invoices or crediting documents.',links:[[cfr('15'),'CACFP cost records'],[ak,'Alaska Food Code']]},
 waste:{title:'Waste',rule:'7 CFR 226.20(j); 45 CFR 1302.102(b)',text:'Operational log supporting production planning and improvement; these provisions do not prescribe a standalone waste form.',links:[[cfr('20'),'Production planning'],[hs('1302-102-achieving-program-goals'),'Program oversight']]},
 cold:{title:'Refrigerator & freezer',rule:'18 AAC 31.234; 7 CFR 226.20(l)',text:'Document storage checks and follow-up. Refrigerated potentially hazardous food: 41°F or below; frozen products stay frozen. Ambient readings alone do not establish food safety. Routine log format is an operational choice.',links:[[ak,'Alaska Food Code'],['https://dec.alaska.gov/eh/fss/resources/temperature-controls/','DEC temperature guidance']]},
 thermal:{title:'Cooking & holding',rule:'18 AAC 31.232; 18 AAC 31.234',text:'Record food, time, internal temperature and applicable cooking duration. Use the food-specific standard, including reheating and cooling rules; a single universal cooking temperature is inappropriate.',links:[[ak,'Alaska Food Code'],['https://dec.alaska.gov/eh/fss/resources/temperature-controls/','DEC time and temperature tables']]},
 cooling:{title:'Cooling & reheating',rule:'18 AAC 31.234',text:'Track time and temperature milestones, method and corrective action for each batch. Compare with the applicable cooling or reheating process in DEC guidance.',links:[[ak,'Alaska Food Code'],['https://dec.alaska.gov/eh/fss/resources/temperature-controls/','DEC cooling and reheating guidance']]},
 dishwasher:{title:'Dishwasher',rule:'18 AAC 31.423, Table H; 31.424(a)(2)–(3), (b)',text:'Verify the machine-specific wash/rinse requirements and sanitation method. Hot-water machines require a utensil-surface indicator; chemical machines need concentration and related checks.',links:[[ak,'Alaska Food Code: warewashing']]},
 sanitizer:{title:'Sanitizer sink',rule:'18 AAC 31.423; 31.424(a)(1), (3), (b), Table I',text:'Document chemical, concentration, temperature, contact time and applicable pH/hardness. Follow the approved product label and code; no universal ppm pass threshold is assumed.',links:[[ak,'Alaska Food Code: sanitizing']]},
 corrective:{title:'Corrective actions',rule:'45 CFR 1302.47(b); 1302.102(b)(1)',text:'Track identified problems, immediate action and verified resolution. This workflow supports oversight; it does not replace required incident reporting.',links:[[hs('1302-47-safety-practices'),'Safety management'],[hs('1302-102-achieving-program-goals'),'Ongoing oversight']]},
 cleaning:{title:'Cleaning & sanitation',rule:'18 AAC 31.420–31.425; 45 CFR 1302.47(b)(6)(ii)',text:'Record cleaning and sanitizing of food-contact surfaces, equipment and utensils. Set frequency to the task, contamination risk and applicable code requirement.',links:[[ak,'Alaska Food Code: cleaning'],[hs('1302-47-safety-practices'),'Safe food preparation']]},
 infant:{title:'Infant feeding',rule:'7 CFR 226.20(b), (d); 45 CFR 1302.44(a)(2)(iv), (viii)',text:'Use individual developmental feeding instructions and infant components. Keep this detail linked to room counts, without counting infant meals twice.',links:[[cfr('20'),'Infant meal patterns'],[hs('1302-44-child-nutrition'),'Developmental feeding']]},
 training:{title:'Training & document register',rule:'7 CFR 226.15(e)(12); 45 CFR 1302.47(b)(4); Alaska DEED CACFP training',text:'Track completion and the location of official attendance/certificate records. Kitchen initials alone do not replace required training participant names in the official record.',links:[['https://education.alaska.gov/cnp/cacfp3','Alaska CACFP training'],[cfr('15'),'Training records']]},
 reports:{title:'Reports & backup',rule:'7 CFR 226.10(d); 45 CFR 1303.24(a)–(b)',text:'Retain claim support for three years after the final claim for its fiscal year, longer for unresolved audits. Protect access. Browser storage and this role selector do not satisfy production security or archival requirements.',links:[[cfr('10'),'Record retention'],[hs('1303-24-maintaining-records'),'Child record protections']]}
};
const f=(key,label,type='text',options=[],required=false)=>({key,label,type,options,required});
const room=f('room','Room','select',rooms,true), meal=f('meal','Meal','select',meals,true);
const notes=f('notes','Notes — no child names','textarea');
const time=f('time','Time observed / service time','time',[],true);
const action=f('action','Corrective action / follow-up reference');
export const schemas={
 counts:{title:'Meal counts',source:'counts',description:'One record per room, meal and date. Enter child counts only in the four stages. Keep classroom source records; kitchen entry is a transcription, not the original observation.',fields:[room,meal,f('enrolled','Enrolled children','integer',[],true),f('attendance','Children present at this meal','integer',[],true),f('requested','Requested child meals','integer',[],true),f('prepared','Prepared child portions','integer',[],true),f('served','Served children — point of service','integer',[],true),f('reimbursable','Reimbursable children — reviewed','integer'),f('staff','Staff meals served','integer',[],true),f('volunteers','Volunteer meals served','integer',[],true),f('visitors','Visitor meals served','integer',[],true),f('laborAdults','Of adult meals: necessary food-service labor','integer',[],true),time,f('sourceRef','Classroom POS sheet / source reference','text',[],true),f('observer','Observer staff initials','initials',[],true),f('family','Sufficient components on tables; family-style procedure followed','select',['Not yet verified','Verified','Exception documented'],true),f('review','Reimbursement review','select',['Pending','Reviewed'],true),f('reviewer','Reviewer staff initials','initials'),f('reason','Count discrepancy / eligibility exception explanation','textarea'),notes]},
 production:{title:'Menu / production records',source:'menu',description:'Enter one food/component line per batch and age group; use common units and record portions available for supervising adults.',fields:[meal,f('age','Age / meal pattern','select',['Birth–5 months','6–11 months','Age 1','Age 2','Ages 3–5'],true),f('food','Food / standardized recipe reference','text',[],true),f('component','Component credited','select',['Milk','Meat/meat alternate','Vegetable','Fruit','Grain','Combination — specify','Noncreditable extra'],true),f('portion','Portion per child + unit','text',[],true),f('planned','Planned child portions','integer',[],true),f('adultPortions','Planned adult portions','integer',[],true),f('quantity','Quantity prepared + unit','text',[],true),f('leftovers','Leftover quantity + unit / disposition'),f('actual','Actual item served / substitution'),f('credit','CN label / PFS / Food Buying Guide reference'),f('wgr','Whole-grain-rich','select',['Not applicable','Yes — documentation held','No']),f('sugar','Cereal/yogurt added-sugar check','select',['Not applicable','Verified against current limit','Needs review']),notes]},
 diets:{title:'Dietary modifications',source:'diets',description:'Initials only; use a distinct local reference to distinguish matching initials. Keep medical statements and emergency plans in the approved confidential system.',fields:[room,f('initials','Child initials only','initials',[],true),f('localRef','Unique kitchen reference','text',[],true),f('category','Category','category',[],true),f('avoid','Foods to avoid / texture needs','textarea',[],true),f('substitute','Approved substitute and preparation / cross-contact instructions','textarea',[],true),f('document','Statement / parent request reference'),f('documentStatus','Documentation','select',['Pending','On file — licensed healthcare professional','On file — registered dietitian','On file — parent request','Not required — within pattern']),f('plan','Emergency action plan location / posting confirmation'),f('end','End date (optional)','date'),notes]},
 presence:{title:'Modified diet attendance',source:'diets',description:'One daily status per dietary record. Present modifications appear in today’s kitchen plan; absence never automatically alters observed meal counts.',fields:[f('dietId','Dietary record','diet',[],true),f('presence','Status for this date','select',['Present','Absent'],true),f('meals','Meals affected','select',['All meals',...meals],true),notes]},
 product:{title:'Product catalog',source:'inventory',description:'Stock is calculated from accepted receipts minus use and stock waste, by lot. Photos remain in this browser and are included in backups.',fields:[f('name','Product name','text',[],true),f('unit','Base stock unit (e.g. can, lb, gallon)','text',[],true),f('package','Package size / conversion to base unit'),f('upc','UPC / barcode'),f('allergens','Label allergens / ingredients'),f('credit','CN label / PFS / crediting reference'),f('location','Storage location'),f('front','Front product photo','photo'),f('back','Back ingredients / nutrition photo','photo'),notes]},
 receiving:{title:'Receiving',source:'inventory',description:'Use the product’s base stock unit consistently. Accepted receipts increase stock. Rejected receipts remain documented without increasing stock.',fields:[f('productId','Product','product',[],true),f('lot','Lot / batch reference','text',[],true),f('quantity','Quantity in base units','positive',[],true),f('vendor','Vendor','text',[],true),f('invoice','Invoice / receipt reference','text',[],true),f('cost','Total line cost ($)','decimal',[],true),f('expiry','Expiration / best-by date','date'),f('temperature','Receiving temperature °F','temperature'),f('condition','Packaging / frozen condition','text',[],true),f('decision','Receipt decision','select',['Accepted','Rejected'],true),action,notes]},
 use:{title:'Inventory use',source:'inventory',description:'Deduct ingredients at issue to production. Record later plate waste separately without deducting stock again.',fields:[f('productId','Product','product',[],true),f('lot','Lot / batch reference','text',[],true),f('quantity','Quantity in base units','positive',[],true),f('purpose','Recipe / production reference','text',[],true),meal,notes]},
 waste:{title:'Waste log',source:'waste',description:'Stock waste deducts inventory. Prepared/plate waste was already issued to production and does not deduct again.',fields:[f('kind','Waste type','select',['Stock waste','Prepared / plate waste'],true),f('productId','Product (required for stock waste)','product'),f('lot','Lot (required for stock waste)'),f('food','Food description','text',[],true),f('quantity','Quantity','positive',[],true),f('unit','Unit (stock waste must use product base unit)','text',[],true),f('reason','Reason','select',['Spoilage','Expired','Damaged','Overproduction','Plate waste','Temperature abuse','Other'],true),f('disposition','Disposition / action','text',[],true),notes]},
 cold:{title:'Refrigerator / freezer temperatures',source:'cold',description:'Record actual observations. Freezers use the equipment target and frozen condition; log review is manual.',fields:[f('equipment','Equipment ID / location','text',[],true),f('kind','Equipment','select',['Refrigerator','Freezer'],true),time,f('temperature','Observed ambient °F','temperature',[],true),f('foodTemp','Food temperature °F if checked','temperature'),f('target','Applicable target / SOP','text',[],true),f('condition','Food frozen / condition'),f('result','Result','select',['Within target','Action required'],true),action,f('recheck','Recheck time / temperature'),notes]},
 thermal:{title:'Cooking / holding temperatures',source:'thermal',description:'Choose the food-specific limit from DEC guidance. Log actual time at temperature; results are reviewed by staff.',fields:[f('food','Food / batch','text',[],true),f('process','Process','select',['Cooking','Hot holding','Cold holding'],true),time,f('temperature','Internal temperature °F','temperature',[],true),f('duration','Time at temperature (seconds/minutes)','text',[],true),f('target','Applicable temperature/time standard','text',[],true),f('result','Result','select',['Within target','Action required'],true),action,f('recheck','Recheck time / temperature'),notes]},
 cooling:{title:'Cooling / reheating',source:'cooling',description:'Use timestamps including the date for overnight batches. Enter actual readings; this prototype does not automatically judge elapsed-time compliance.',fields:[f('food','Food / batch','text',[],true),f('process','Process','select',['Cooling cooked food','Cooling room-temperature preparation','Reheating for hot holding'],true),f('method','Method / container depth','text',[],true),f('start','Start timestamp','datetime-local',[],true),f('startTemp','Start °F','temperature',[],true),f('mid','Intermediate timestamp','datetime-local'),f('midTemp','Intermediate °F','temperature'),f('end','Finish timestamp','datetime-local',[],true),f('endTemp','Finish °F','temperature',[],true),f('target','Applicable time/temperature standard','text',[],true),f('result','Result','select',['Within target','Action required'],true),action,notes]},
 dishwasher:{title:'Dishwasher checks',source:'dishwasher',description:'Record machine-specific limits from the data plate and code. Complete applicable heat or chemical readings.',fields:[f('equipment','Machine ID','text',[],true),time,f('method','Sanitizing method','select',['Hot water','Chemical'],true),f('wash','Wash °F','temperature',[],true),f('rinse','Final rinse manifold °F','temperature'),f('surface','Utensil surface °F / irreversible indicator result'),f('chemical','Chemical / label'),f('ppm','Measured ppm','decimal'),f('contact','Contact time / pH / hardness if applicable'),f('target','Data plate / code / label target','text',[],true),f('result','Result','select',['Within target','Action required'],true),action,notes]},
 sanitizer:{title:'Sanitizer sink checks',source:'sanitizer',description:'Select the method and document the applicable code/label limits. Chemical strengths vary; compare using the correct test strips.',fields:[f('location','Sink / station','text',[],true),time,f('chemical','Chemical or hot-water method','text',[],true),f('ppm','Measured ppm (chemical)','decimal'),f('temperature','Water °F','temperature',[],true),f('contact','Contact time in seconds','positive',[],true),f('ph','pH / hardness when applicable'),f('target','Label / Table I target including concentration and contact time','text',[],true),f('test','Test strip / thermometer used','text',[],true),f('result','Result','select',['Within target','Action required'],true),action,notes]},
 corrective:{title:'Corrective actions',source:'corrective',description:'Keep the original observation and reference it here. Close only after recording verification.',fields:[f('reference','Related record ID / inspection reference','text',[],true),f('issue','Issue / hazard','textarea',[],true),f('action','Immediate action / food disposition','textarea',[],true),f('owner','Responsible staff initials','initials',[],true),f('due','Follow-up due date','date',[],true),f('status','Status','select',['Open','In progress','Closed'],true),f('verification','Verification / recheck result'),f('verifiedBy','Verified by staff initials','initials'),notes]},
 cleaning:{title:'Cleaning / sanitation',source:'cleaning',description:'Use the facility’s cleaning schedule; record completion and any missed task.',fields:[f('area','Area / equipment','text',[],true),f('task','Task / method','text',[],true),f('frequency','Required frequency / SOP reference','text',[],true),time,f('agent','Cleaning agent / sanitizer / dilution'),f('result','Result','select',['Complete','Action required'],true),action,notes]},
 infant:{title:'Infant feeding detail',source:'infant',description:'Birth–5 months and 6–11 months have separate patterns. Link each entry to classroom POS evidence; these records are excluded from aggregate meal totals.',fields:[room,f('initials','Infant initials only','initials',[],true),f('localRef','Kitchen reference','text',[],true),f('age','Age band','select',['Birth–5 months','6–11 months'],true),meal,time,f('milk','Breastmilk / iron-fortified formula / direct breastfeeding','text',[],true),f('amount','Amount offered + unit / breastfeeding documentation','text',[],true),f('solids','Developmental readiness and solids/components + quantities'),f('plan','Individual feeding instruction / parent preference reference','text',[],true),f('handling','Storage / bottle label / preparation check'),f('sourceRef','Related classroom POS source','text',[],true),notes]},
 training:{title:'Training / document register',source:'training',description:'Track kitchen training and references to official records. Do not upload child records or identifying medical documents.',fields:[f('topic','Topic / certificate','text',[],true),f('location','Training location / provider','text',[],true),f('participants','Staff initials / official attendance register reference','text',[],true),f('document','Official document location','text',[],true),f('due','Renewal / review date','date'),notes]}
};
export const sections=[['today','Today','◷'],['menu','Weekly menu','▦'],['counts','Meal counts','▤'],['diets','Dietary needs','♡'],['inventory','Inventory','□'],['logs','Kitchen logs','✓'],['reports','Reports & backup','↗'],['sources','Compliance guide','ⓘ']];

