'use strict';
const substitutionColumns=[['name','Name'],['room','Room Number'],['component','Component'],['avoid','Avoid'],['substitute','Substitute']];
let substitutionSort={key:'name',direction:1};
function validSubstitutions(rows){return rows===undefined||(Array.isArray(rows)&&rows.every(r=>r&&typeof r.id==='string'&&substitutionColumns.every(([key])=>typeof r[key]==='string')))}
function sortedSubstitutions(rows,key,direction){return [...rows].sort((a,b)=>direction*a[key].localeCompare(b[key],undefined,{numeric:true,sensitivity:'base'}))}
function renderSubstitutions(){
  const rows=sortedSubstitutions(db.substitutions||[],substitutionSort.key,substitutionSort.direction);
  $('#content').innerHTML=`<div class="page-title"><div><div class="eyebrow">MEAL ACCOMMODATIONS</div><h1>Substitutions</h1><p>Keep approved food substitutions together by name and room.</p></div><button class="primary" id="addSubstitution">+ Add row</button></div><section class="panel"><p>Click a column heading to sort; click again to reverse the order.</p><div class="substitution-scroll"><table class="substitution-table"><thead><tr>${substitutionColumns.map(([key,label])=>`<th scope="col" aria-sort="${substitutionSort.key===key?(substitutionSort.direction===1?'ascending':'descending'):'none'}"><button data-sort="${key}">${label}${substitutionSort.key===key?(substitutionSort.direction===1?' ↑':' ↓'):''}</button></th>`).join('')}<th scope="col">Actions</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${substitutionColumns.map(([key])=>`<td>${esc(r[key])}</td>`).join('')}<td><button data-edit-substitution="${esc(r.id)}" aria-label="Edit substitution for ${esc(r.name)}">Edit</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No substitutions yet. Add a row to get started.</td></tr>'}</tbody></table></div><p class="menu-hint">Saved on this device and included in backups. Use only the identifying details your facility permits; keep medical documents in your approved confidential system.</p></section>`;
  $('#addSubstitution').onclick=()=>openSubstitution();
  document.querySelectorAll('[data-sort]').forEach(button=>button.onclick=()=>{const key=button.dataset.sort;substitutionSort={key,direction:substitutionSort.key===key?-substitutionSort.direction:1};renderSubstitutions();document.querySelector(`[data-sort="${key}"]`).focus()});
  document.querySelectorAll('[data-edit-substitution]').forEach(button=>button.onclick=()=>openSubstitution(button.dataset.editSubstitution));
}
function openSubstitution(id){
  const row=(db.substitutions||[]).find(r=>r.id===id)||{},dialog=document.createElement('dialog');
  dialog.setAttribute('aria-labelledby','substitutionTitle');
  dialog.innerHTML=`<form><div class="section-head"><h2 id="substitutionTitle">${id?'Edit substitution':'Add substitution'}</h2><button type="button" data-close aria-label="Close substitution">×</button></div>${substitutionColumns.map(([key,label])=>`<label class="field">${label}${['avoid','substitute'].includes(key)?`<textarea name="${key}" required>${esc(row[key]||'')}</textarea>`:`<input name="${key}" required value="${esc(row[key]||'')}">`}</label>`).join('')}<p data-error role="alert"></p><div class="menu-confirm-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save row</button></div></form>`;
  dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.onclose=()=>dialog.remove();
  dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target),record={id:id||crypto.randomUUID()};for(const [key] of substitutionColumns)record[key]=String(form.get(key)||'').trim();if(substitutionColumns.some(([key])=>!record[key])){dialog.querySelector('[data-error]').textContent='Fill in all five fields.';return}const old=db.substitutions;db.substitutions=id?(old||[]).map(r=>r.id===id?record:r):[...(old||[]),record];if(!save()){db.substitutions=old;dialog.querySelector('[data-error]').textContent='Could not save. Your existing rows are unchanged.';return}dialog.close();renderSubstitutions();notify('Substitution saved')};
  document.body.append(dialog);dialog.showModal();
}
