'use strict';
// Workflow records are additive: old backups and all original records remain readable.
const wfMeals=['Breakfast','Lunch','Snack'];
const wfComponents=['milk','meat','vegetable','fruit','grain'];
const wfComponentLabels=['Milk (fl oz)','Meat / alternate (oz eq)','Vegetable (cups)','Fruit (cups)','Grain (oz eq)'];
const wfAges=['1–2','3–5','6–12','Infant'];
const wfRound=n=>Math.round((n+Number.EPSILON)*1000000)/1000000;
const wfNorm=s=>String(s||'').trim().replace(/\s+/g,' ').toLowerCase();
function wfEmpty(){return {version:1,rooms:[],recipes:[],batches:[],services:{},attendance:{},safety:{},infants:[],closeouts:{},trips:[],audit:[],settings:{safety:'Opening refrigerator / freezer checks\nCooking / holding temperatures\nCooling / cleaning checks',extra:'',sponsor:''}}}
function wf(){if(!db.workflow)db.workflow=wfEmpty();if(!db.workflow.started)db.workflow.started=today();return db.workflow}
function validWorkflow(w){
  if(w===undefined)return true;
  const obj=x=>x&&typeof x==='object'&&!Array.isArray(x),rows=(x,test)=>Array.isArray(x)&&x.every(r=>obj(r)&&typeof r.id==='string'&&test(r));
  const num=x=>Number.isFinite(+x)&&+x>=0;
  return obj(w)&&w.version===1&&rows(w.rooms,r=>typeof r.name==='string'&&wfAges.includes(r.age)&&num(r.expected))&&rows(w.recipes,r=>typeof r.name==='string'&&+r.yield>0&&Array.isArray(r.ingredients)&&r.ingredients.every(i=>typeof i.itemId==='string'&&num(i.quantity))&&obj(r.components)&&Array.isArray(r.portions)&&r.portions.length===3&&r.portions.every(num))&&rows(w.batches,r=>typeof r.itemId==='string'&&num(r.quantity)&&typeof r.expires==='string')&&rows(w.infants,r=>typeof r.date==='string')&&rows(w.trips,r=>typeof r.name==='string')&&Array.isArray(w.audit)&&w.audit.every(a=>obj(a)&&typeof a.at==='string'&&typeof a.label==='string')&&['services','attendance','safety','closeouts','settings'].every(k=>obj(w[k]))&&Object.values(w.services).every(s=>obj(s)&&Array.isArray(s.rooms)&&Array.isArray(s.items)&&Array.isArray(s.usage)&&Array.isArray(s.checks)&&s.rooms.every(r=>obj(r)&&typeof r.id==='string'&&typeof r.name==='string'&&wfAges.includes(r.age))&&s.items.every(i=>obj(i)&&typeof i.name==='string'&&(!i.recipe||(obj(i.recipe)&&Array.isArray(i.recipe.portions)&&Array.isArray(i.recipe.ingredients)&&obj(i.recipe.components))))&&s.usage.every(u=>obj(u)&&typeof u.batchId==='string'&&num(u.quantity))&&s.checks.every(c=>obj(c)&&typeof c.label==='string'))&&Object.values(w.safety).every(s=>obj(s)&&Array.isArray(s.checks)&&s.checks.every(c=>obj(c)&&typeof c.label==='string'))&&Object.values(w.attendance).every(obj)&&Object.values(w.closeouts).every(obj);
}
function wfTransaction(label,change){const before=structuredClone(db);try{change();wf().audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),label});if(!save())throw Error('Could not save. Export a backup and free browser storage.');return true}catch(error){db=before;throw error}}
function wfSnapshot(label,before,after,reason){wf().audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),label,reason,before:structuredClone(before),after:structuredClone(after)})}
function wfBatches(itemId,date=today()){return wf().batches.filter(b=>b.itemId===itemId&&+b.quantity>0&&(!b.expires||b.expires>=date)).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999')||(a.received||'').localeCompare(b.received||''))}
function wfAvailable(itemId,date=today()){return wfRound(wfBatches(itemId,date).reduce((n,b)=>n+ +b.quantity,0))}
// Reconcile legacy/manual aggregate changes into dated adjustments; never discard stock.
function wfReconcile(){const w=wf();for(const item of db.inventory){const total=w.batches.filter(b=>b.itemId===item.id).reduce((n,b)=>n+ +b.quantity,0),difference=wfRound(+item.quantity-total);if(!Number.isFinite(difference))continue;
  if(difference>0)w.batches.push({id:crypto.randomUUID(),itemId:item.id,quantity:difference,received:today(),expires:item.expires||'',location:item.location||'',opened:'',thawed:'',lot:'',source:total?'Manual stock adjustment':'Opening balance',notes:'Confirm batch dates and location.'});
  if(difference<0){let remaining=-difference;for(const batch of w.batches.filter(b=>b.itemId===item.id).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999'))){const take=Math.min(+batch.quantity,remaining);batch.quantity=wfRound(+batch.quantity-take);remaining=wfRound(remaining-take);if(!remaining)break}}
}}
function wfReceiveBatches(delivery){for(const line of delivery.items){if(line.decision!=='accepted'||+line.quantity<=0)continue;const item=db.inventory.find(i=>receiptItemKey(i)===receiptItemKey({name:resolveInventoryAlias(line.name),unit:line.unit}));if(item)wf().batches.push({id:crypto.randomUUID(),itemId:item.id,quantity:+line.quantity,received:delivery.date,expires:line.expires||'',location:line.storage||'',lot:line.lot||'',opened:'',thawed:'',source:'Delivery '+delivery.id,notes:line.notes||''})}}
function wfRecipe(name){const matches=wf().recipes.filter(r=>!r.archived&&wfNorm(r.name)===wfNorm(name));return matches.length===1?matches[0]:null}
function wfMenuItems(date,meal){const day=(parse(date).getDay()+6)%7;return (day<5?db.menus?.[menuMonday(date)]?.cells[meal]?.[day]||'':'').split(/\n|;/).map(s=>s.trim()).filter(Boolean)}
function wfRoomPlan(date,meal){return wf().rooms.filter(r=>!r.archived&&r.age!=='Infant').map(r=>({id:r.id,name:r.name,age:r.age,expected:String(wf().attendance[date]?.[r.id]?.expected??r.expected),actualAttendance:wf().attendance[date]?.[r.id]?.actual??'',served:'',substitution:'',substitutions:(db.substitutions||[]).filter(s=>wfNorm(s.room)===wfNorm(r.name)).map(s=>structuredClone(s))}))}
function wfPlan(date,meal){return wfMenuItems(date,meal).map(name=>({name,recipe:wfRecipe(name)?structuredClone(wfRecipe(name)):null}))}
function wfScale(recipe,rooms){return wfRound(rooms.reduce((n,r)=>n+(+r.expected||0)*(+recipe.portions[wfAges.indexOf(r.age)]||0),0))}
function wfNeeds(items,rooms){const need=new Map(),unresolved=[];for(const entry of items){const recipe=entry.recipe;if(!recipe){unresolved.push(entry.name);continue}const servings=wfScale(recipe,rooms);for(const ingredient of recipe.ingredients){const item=db.inventory.find(i=>i.id===ingredient.itemId);if(!item){unresolved.push(entry.name+' — missing inventory item');continue}if(ingredient.unit&&receiptUnit(ingredient.unit)!==receiptUnit(item.unit)){unresolved.push(entry.name+' — inventory unit changed for '+item.name);continue}const key=item.id;need.set(key,wfRound((need.get(key)||0)+(+ingredient.quantity*servings/+recipe.yield)))}}return {need,unresolved}}
function wfShoppingPlan(week){
  const need=new Map(),shortages=new Map(),unresolved=[],virtual=structuredClone(wf().batches);
  for(let day=0;day<5;day++){const date=parse(week);date.setDate(date.getDate()+day);const value=iso(date);
    for(let meal=0;meal<3;meal++){const result=wfNeeds(wfPlan(value,meal),wfRoomPlan(value,meal));if(!wfMenuItems(value,meal).length)unresolved.push(value+' '+wfMeals[meal]+': menu missing');result.unresolved.forEach(n=>unresolved.push(value+' '+wfMeals[meal]+': '+n));
      for(const [id,quantity] of result.need){need.set(id,wfRound((need.get(id)||0)+quantity));let remainder=quantity;
        for(const batch of virtual.filter(b=>b.itemId===id&&+b.quantity>0&&(!b.expires||b.expires>=value)).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999'))){const take=Math.min(+batch.quantity,remainder);batch.quantity=wfRound(+batch.quantity-take);remainder=wfRound(remainder-take);if(!remainder)break}
        shortages.set(id,wfRound((shortages.get(id)||0)+remainder));
      }
    }
  }
  return {unresolved,rows:[...need].map(([itemId,quantity])=>{const item=db.inventory.find(i=>i.id===itemId),have=wfAvailable(itemId,week),pending=(db.deliveries||[]).filter(d=>d.status==='draft').reduce((n,d)=>n+d.items.filter(l=>receiptItemKey({name:resolveInventoryAlias(l.name),unit:l.unit})===receiptItemKey(item)).reduce((s,l)=>s+ +l.quantity,0),0);return {itemId,name:item.name,unit:item.unit,need:quantity,have,pending,buy:shortages.get(itemId)||0}})}
}

function wfDeduct(usage,date){for(const row of usage){const batch=wf().batches.find(b=>b.id===row.batchId);if(!batch||+row.quantity<0||!Number.isFinite(+row.quantity))throw Error('Choose an existing batch and a valid quantity.');if(batch.expires&&batch.expires<date&&+row.quantity>0)throw Error('Expired stock cannot be selected for food production.');if(+row.quantity>+batch.quantity)throw Error('Not enough stock remains in a selected batch.');const item=db.inventory.find(i=>i.id===batch.itemId);if(!item)throw Error('An inventory item was removed. Correct the usage rows.');batch.quantity=wfRound(+batch.quantity- +row.quantity);item.quantity=String(wfRound(+item.quantity- +row.quantity))}}
function wfRestoreUsage(usage){for(const row of usage){const b=wf().batches.find(x=>x.id===row.batchId),item=b&&db.inventory.find(x=>x.id===b.itemId);if(!b||!item)throw Error('Cannot correct usage because its inventory record was removed.');b.quantity=wfRound(+b.quantity+ +row.quantity);item.quantity=String(wfRound(+item.quantity+ +row.quantity))}}
function wfDayIssues(date){const issues=[];if(wf().closeouts[date]?.noService)return dayData(date).tasks.filter(t=>!t.done&&!String(t.id).startsWith('default-')&&(!t.due||t.due<=today())).map(t=>t.title);const weekday=parse(date).getDay()%6!==0;if(!weekday&&!Object.keys(wf().services).some(k=>k.startsWith(date)))return issues;
  for(let m=0;m<3;m++){const s=wf().services[date+'|'+m];if(!s?.complete)issues.push(wfMeals[m]+' service record missing');}
  if(!wf().safety[date]?.complete)issues.push('Safety checks unfinished');if(wf().rooms.some(r=>!r.archived&&r.age==='Infant')&&!wf().infants.some(r=>r.date===date))issues.push('Infant feeding records missing');
  for(const t of dayData(date).tasks){if(!t.done&&!String(t.id).startsWith('default-')&&(!t.due||t.due<=today()))issues.push(t.title)}return issues;
}
function wfMealCheck(items,meal,ageGroup){const index=wfAges.indexOf(ageGroup),totals=Object.fromEntries(wfComponents.map(k=>[k,0]));if(index<0||index>2)return 'Use individual infant feeding records.';let unknown=false;for(const entry of items){const r=entry.recipe;if(!r){unknown=true;continue}for(const key of wfComponents)totals[key]+= (+r.components[key]||0)*(+r.portions[index]||0)}
  const patterns=[[[4,0,0,.25,.5],[6,0,0,.5,.5],[8,0,0,.5,1]],[[4,1,.125,.125,.5],[6,1.5,.25,.25,.5],[8,2,.5,.25,1]],[[4,.5,.5,.5,.5],[4,.5,.5,.5,.5],[8,1,.75,.75,1]]],min=patterns[meal][index];let missing=[];
  if(meal===0){if(totals.milk<min[0])missing.push('milk');if(totals.vegetable+totals.fruit<min[3])missing.push('fruit / vegetable');if(totals.grain<min[4])missing.push('grain or approved breakfast alternate')}
  else if(meal===1)missing=wfComponents.filter((k,i)=>totals[k]+1e-8<min[i]);
  else if(wfComponents.filter((k,i)=>totals[k]+1e-8>=min[i]).length<2)missing=['two different components'];
  return (unknown?'Unlinked foods; totals incomplete. ':'')+(missing.length?'Check '+missing.join(', ')+'.':'Entered component amounts meet the basic pattern.')+' Review allowed alternatives, milk type, WGR, sugar, juice and substitutions separately.';
}
function wfReceiptDraft(rows,filename,text,file){const records=receiptInventoryRecords(rows,filename);if(!records.length)throw Error('Select at least one item.');const fingerprint=JSON.stringify(records.map(r=>[wfNorm(r.name),+r.quantity,receiptUnit(r.unit)]).sort());if((db.deliveries||[]).some(d=>d.receiptFingerprint===fingerprint&&d.date===selected))throw Error('A receipt with these items and quantities already exists for this date. Open its receiving record instead.');const delivery={id:crypto.randomUUID(),supplier:filename||'Shopping receipt',receiver:'',date:selected,invoice:'',notes:'Receipt draft — verify goods and receiving checks before posting.',status:'draft',receiptFingerprint:fingerprint,receiptText:text,...(file?{file}:{}),items:records.map(r=>({name:r.name,quantity:r.quantity,unit:r.unit,ordered:'',decision:'hold',expires:'',storage:'',temperature:'',notes:r.receipt.originalName}))};wfTransaction('Receipt saved as receiving draft',()=>{db.deliveries=[...(db.deliveries||[]),delivery]});return delivery.id}
