'use strict';
// Extend the existing workspace without replacing its storage key or historical data.
const wfOriginalSave=save;
save=function(){const prior=structuredClone(db.workflow);wfReconcile();if(wfOriginalSave())return true;db.workflow=prior;return false};
const wfOriginalRender=render,wfOriginalCalendar=renderCalendar,wfOriginalRecords=renderRecords,wfOriginalMenu=renderMenu,wfOriginalStatus=status,wfOriginalAssessment=menuItemAssessment,wfOriginalReview=openMenuReview;
const wfOriginalDayData=dayData,wfOriginalDeliveries=renderDeliveries;
dayData=function(date){if(db.days[date])return db.days[date];if(db.workflow&&date>=(db.workflow.started||today()))return {tasks:[]};return wfOriginalDayData(date)};
fields.task.push(['due','Task due date','date']);
renderDeliveries=function(){wfOriginalDeliveries();const held=(db.deliveries||[]).filter(d=>d.status==='posted').flatMap(d=>d.items.map((i,index)=>({d,i,index})).filter(x=>x.i.decision==='hold'));if(!held.length)return;const p=document.createElement('section');p.className='panel';p.innerHTML='<h2>Held items · follow up</h2>'+held.map(({d,i,index})=>{const linked=(db.deliveries||[]).find(x=>x.holdSource===d.id+'|'+index);return `<article class="record"><div><strong>${esc(i.name)}</strong><p>${esc(d.supplier)} · ${esc(i.quantity)} ${esc(i.unit)} · ${linked?'Resolution record created':'Not in available stock'}</p></div><button data-held-source="${esc(d.id)}" data-held-index="${index}">${linked?'Open resolution':'Resolve held item'}</button></article>`}).join('');$('#content').append(p);p.querySelectorAll('[data-held-source]').forEach(b=>b.onclick=()=>{const source=b.dataset.heldSource+'|'+b.dataset.heldIndex,existing=(db.deliveries||[]).find(x=>x.holdSource===source);if(existing){openDelivery(existing.id);return}const original=db.deliveries.find(x=>x.id===b.dataset.heldSource),line=original.items[+b.dataset.heldIndex],resolution={id:crypto.randomUUID(),supplier:original.supplier,date:today(),invoice:'',receiver:'',status:'draft',holdSource:source,notes:'Resolution of held item from invoice '+(original.invoice||original.id)+'. Record the decision and corrective action.',items:[{...structuredClone(line),decision:'hold'}]};try{wfTransaction('Held delivery follow-up',()=>db.deliveries.push(resolution));render();openDelivery(resolution.id)}catch(e){notify(e.message)}})};
Object.assign(names,{today:'Today’s Kitchen',recipes:'Recipes & food portions',setup:'Kitchen setup',records:'Records & closeout',calendar:'Calendar'});
render=function(){wf();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewLabel').textContent=names[view];if(view==='today')wfToday();else if(view==='recipes')wfRecipes();else if(view==='setup')wfSetup();else if(view==='records')wfRecords();else wfOriginalRender()};
renderRecords=function(){wfOriginalRecords();if(view==='inventory'){wfInventoryPanel();document.querySelectorAll('[data-delete]').forEach(b=>{const original=b.onclick;b.onclick=()=>{const id=b.dataset.delete;if(wf().batches.some(x=>x.itemId===id)||wf().recipes.some(r=>r.ingredients.some(i=>i.itemId===id))){notify('This item has stock history or recipe links. Adjust remaining stock to zero instead of deleting it.');return}original()}})}if(view==='shopping')wfPurchasingPanel()};
renderCalendar=function(){wfOriginalCalendar();const legend=document.querySelector('.legend');if(legend)legend.innerHTML='<span><i class="dot green"></i>Records finished</span><span><i class="dot yellow"></i>Due today / outstanding</span><span><i class="dot red"></i>Past service date or task deadline</span><span>Historical checklists retain their original seven-day rule.</span>'; const p=document.createElement('section');p.className='panel';p.innerHTML=`<div class="section-head"><h2>Kitchen workflow · ${selected}</h2><button id="wfOpenDay" class="primary">Open daily preparation & records</button></div><p>${wfDayIssues(selected).map(esc).join(' · ')||'No unfinished service records.'}</p><p>Service and safety records are due on the day of service. Older checklist history is retained below the calendar.</p>`;$('#content').insertBefore(p,$('#content').children[3]||null);$('#wfOpenDay').onclick=()=>wfGo('today')};
status=function(date){if(!db.workflow||date<(db.workflow.started||today()))return wfOriginalStatus(date);if(date>today())return 'neutral';if(parse(date).getDay()%6===0&&!Object.keys(wf().services).some(k=>k.startsWith(date)))return wfOriginalStatus(date);const issues=wfDayIssues(date);return issues.length?((date<today()&&issues.some(i=>/service record missing|Safety checks unfinished|Infant feeding records missing/.test(i)))||dayData(date).tasks.some(t=>!t.done&&t.due&&t.due<today())?'red':'yellow'):'green'};
menuItemAssessment=function(text){const original=wfOriginalAssessment(text),recipe=db.workflow&&wfRecipe(text);if(recipe?.reviewer&&recipe.reviewDate&&(recipe.evidence||recipe.documentId||recipe.labelId)&&!recipe.archived)return {state:'green',label:'Review recorded',reason:'Linked to '+recipe.name+'; review recorded by '+recipe.reviewer+' on '+recipe.reviewDate+'. Verify the actual product, serving size, age group and whole meal. This is a stored human review, not automatic certification.'};return original};
openMenuReview=function(action,item){if(action==='recipe'){const r=wfRecipe(item);wfRecipeForm(r?.id,item);return}wfOriginalReview(action,item)};
renderMenu=function(){wfOriginalMenu();const panel=document.createElement('section');panel.className='panel';panel.innerHTML=`<div class="section-head"><h2>Recipes & preparation links</h2><button id="wfPublicMenu">Download public menu</button></div><p>Insert a saved recipe name to link its ingredients, age-group portions and evidence. Save this week before preparing or building a shopping list. Public menus contain food names only.</p><div class="wf-actions"><label class="menu-week">Recipe / food<select id="wfChooseRecipe"><option value="">Choose recipe</option>${wf().recipes.filter(r=>!r.archived).map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label><label class="menu-week">Day<select id="wfChooseDay">${menuDays.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></label><label class="menu-week">Meal<select id="wfChooseMeal">${wfMeals.map((m,i)=>`<option value="${i}">${m}</option>`).join('')}</select></label><button id="wfInsertRecipe">Add to meal</button><button id="wfMenuRecipe">+ Create recipe / food</button><button id="wfMenuNeeds">Build shopping list</button></div><details><summary>Meal portion checks · linked recipes only</summary><p>These checks use entered recipe contributions. Allowed alternatives and special diets need human review.</p>${menuDays.map((day,c)=>`<h3>${day}</h3>${wfMeals.map((meal,r)=>{const items=menuDraft.cells[r][c].split(/\n|;/).map(s=>s.trim()).filter(Boolean).map(name=>({name,recipe:wfRecipe(name)}));return `<p><strong>${meal}</strong><br>${[...new Set(wf().rooms.filter(x=>!x.archived&&x.age!=='Infant').map(x=>x.age))].map(a=>esc(a)+': '+esc(wfMealCheck(items,r,a))).join('<br>')||'Add room age groups in Kitchen setup.'}</p>`}).join('')}`).join('')}</details>`;
  // Keep the saved cycle library at the bottom.
  const library=$('#cyclesHeading')?.closest('section');$('#content').insertBefore(panel,library||null);$('#wfMenuRecipe').onclick=()=>wfRecipeForm();$('#wfMenuNeeds').onclick=wfShopping;$('#wfInsertRecipe').onclick=()=>{const recipe=wf().recipes.find(r=>r.id===$('#wfChooseRecipe').value);if(!recipe)return;const r=+$('#wfChooseMeal').value,c=+$('#wfChooseDay').value;menuDraft.cells[r][c]=[menuDraft.cells[r][c],recipe.name].filter(Boolean).join('\n');menuDirty=true;renderMenu()};$('#wfPublicMenu').onclick=()=>wfPrintDocument('Menu week '+menuWeek,`<table><tr><th>Meal</th>${menuDays.map(d=>'<th>'+d+'</th>').join('')}</tr>${wfMeals.map((m,r)=>'<tr><th>'+m+'</th>'+menuDraft.cells[r].map(text=>'<td><pre>'+esc(text)+'</pre></td>').join('')+'</tr>').join('')}</table>`)
};
const wfNavigation=[['TODAY',[['today','Today’s Kitchen'],['calendar','Calendar']]],['PLAN',[['menu','Menus'],['recipes','Recipes & food portions'],['substitutions','Substitutions']]],['SUPPLIES',[['inventory','Inventory & stock batches'],['shopping','Shopping & trips'],['deliveries','Receiving'],['mileage','Mileage log']]],['RECORDS & HELP',[['records','Records & closeout'],['labels','Product documentation'],['documents','Paperwork library'],['compliance','Compliance Guide'],['setup','Kitchen setup']]]];
document.querySelector('nav').innerHTML=wfNavigation.map(([label,links])=>`<div class="wf-nav-group">${label}</div>${links.map(([v,label])=>`<button data-view="${v}">${label}</button>`).join('')}`).join('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>wfGo(b.dataset.view));
document.querySelector('footer').innerHTML='Saved in this browser · Download recovery backups regularly. Use facility-approved identifiers and keep medical documents in your confidential system.<br>Colors show workflow status and recorded food reviews, not a CACFP compliance determination.';
const wfOriginalBackup=$('#backup').onclick;$('#backup').onclick=()=>{wfOriginalBackup();localStorage.setItem('cc-kitchen-last-backup',today());notify('Full recovery backup downloaded')};
wf();if(!wf().started)wf().started=today();wfReconcile();view='today';render();
